% The next command tells RStudio to do "Compile PDF" on book.Rnw,
% instead of this chapter, thereby eliminating the need to switch back to book.Rnw 
% before making the book.
%!TEX root = ../../book.Rnw


%#############################################################
\chapter{Carbon intensity of energy}
\label{chap:carbon_intensity}
%#############################################################

As noted in Chapter~\ref{chap:},
**** Be sure to make this point earlier in the book ****
the economy is society's metabolism.
As such, the economy exhibits characteristics of a metabolism:
it ingests material and emits waste.
These characteristics of the economic metabolism are captured by the 
final term in Equation~\ref{eq:IPARC}, 
the contamination intensity of resource extraction and consumption ($c$).
Resource extraction was covered in Chapter~\ref{chap:resource_intensity}.
Environmental contamination is discussed in this chapter.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Contamination intensity of resource extraction}
\label{sec:contamination_intensity}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The contamination intensity of resource extraction ($c$)
represents the amount of environmental contamination (emitted waste)
per unit of resource extracted and consumed (ingested material).
Examples of environmental contamination include
water eutrophication (from fertilizer runoff), 
SO$_2$ emissions (from burning sulfurous coal), 
CO$_2$ emissions (from burning fossil fuels), 
desertification (due to overcultivation of crops, overgrazing of livestock, and alien species invasion), and 
species losses (due to habitat loss, environmental toxins, and over-exploitation).
With reference to a few of the critical materials in Table~\ref{tab:CRMs}, 
specific examples of the environmental contamination caused by material extraction include:
%
\begin{itemize}

  \item air, water, and soil pollution~\cite{Lee:2017ui} (environmental contamination) in the form of
        bauxite dust,
        sulfur dioxide (SO$_2$), and 
        nitrous oxides (NO$_\mathrm{x}$) emissions
        from bauxite mining (material extraction),

  \item Toxic tailings (environmental contamination)
        from Tungsten (material extraction) 
        mining operations~\cite{Lee:2021tz}, and
        
  \item Deforestation and reduced forest quality~\cite{Kissinger:2020ut} (environmental contamination)
        to make way for rubber plantations (material extraction)
        in southeast Asia.

\end{itemize}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Prime example: carbon intensity of energy}
\label{sec:carbon_intensity_of_energy}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

In this book, 
the prime example of environmental contamination is carbon dioxide emissions, and 
the prime example of material extraction and consumption is energy
of all forms.
Thus, the prime example for $c$ is the CO$_2$ intensity of energy.
The units for the CO$_2$ intensity of energy are,
e.g., in tonnes of CO$_2$ emitted per MJ of energy consumed.

The yearly rate of CO$_2$ emitted since 1800 is shown in Figure~\ref{fig:CarbonEmissionsGraph}.
The clear trend is upward, with small drops corresponding to years of economic recession.


<<CarbonEmissionsGraph, fig.cap="World CO$_2$ emissions~\\cite{Ritchie:2021vw}. The years 1932, 1945, 1974, 1982, 1992, and 2009 are highlighted with vertical lines to demonstrate that economic recessions temporarily reduce energy consumption and CO$_2$ emissions.">>=
CO2_emissions <- readxl::read_excel(file.path("chapters", "ch06-CarbonIntensity", "datasets", "annual-co2-emissions-per-country.xlsx"), 
                   sheet = "data to plot")

CO2_emissions %>% 
  dplyr::filter(Year >= 1800) %>% 
  dplyr::mutate(
    CO2_emissions_Gt = CO2_emissions_tonnes / 1e9
  ) %>% 
  ggplot2::ggplot(mapping = ggplot2::aes_string(x = "Year", y = "CO2_emissions_Gt")) + 
  ggplot2::geom_line(size = 1) + 
  ggplot2::geom_vline(xintercept = c(1932, 1945, 1974, 1982, 1992, 2009), size = 0.2) +
  ggplot2::labs(x = NULL,
                y = expression("World "*CO[2]*" emissions [Gt/year]")) +
  
  MKHthemes::xy_theme()
@


The carbon intensity of energy (the prime example for $c$)
is shown in Figure~\ref{fig:CarbonIntensityGraph}.
The line in Figure~\ref{fig:CarbonIntensityGraph}
demonstrates the effect of the long energy transition 
from traditional biofuels to fossil fuels from 1800 to today.
Traditional biofuels are carbon neutral, 
because any CO$_2$ released by combustion was
already sequestered into the biomass as it grew to maturity.
Fossil fuels are not carbon neutral; 
their combustion releases CO$_2$ that was sequestered millions of years ago.


<<CarbonIntensityGraph, fig.cap="Carbon intensity of energy, $c$ in the Kaya identity. The line represents the ratio of Figure~\\ref{fig:CarbonEmissionsGraph} and Figure~\\ref{fig:PrimaryEnergyGraph} in each year.">>=
dplyr::inner_join(
  CO2_emissions, 
  primary_energy %>% 
    dplyr::group_by(Year) %>% 
    dplyr::summarise(energy_EJ = sum(energy_EJ)), 
  by = "Year"
) %>% 
  dplyr::mutate(
    CO2_intensity_Mt_per_EJ = CO2_emissions_tonnes / 1e6 / energy_EJ, 
  ) %>% 
  ggplot2::ggplot(mapping = ggplot2::aes_string(x = "Year", y = "CO2_intensity_Mt_per_EJ")) + 
  ggplot2::geom_line(size = 1) +
  ggplot2::labs(x = NULL,
                y = expression("Carbon intensity of energy (c) [Mt "*CO[2]/EJ*"]")) +
  
  MKHthemes::xy_theme()
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Reducing the carbon intensity of energy}
\label{sec:reducing_c}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\cleardoublepage

