% The next command tells RStudio to do "Compile PDF" on book.Rnw,
% instead of this chapter, thereby eliminating the need to switch back to book.Rnw 
% before making the book.
%!TEX root = ../../book.Rnw


%#############################################################
\chapter{Impact of resources~\Xparen{}}
\label{chap:impact_intensity}
%#############################################################
% \epigraph{Normal human activity is worse for nature than the biggest 
% nuclear accident in history.}{Martin Cruz Smith}
%\epigraph{Environmental pollution is an incurable disease. It can only
%be prevented.}{Barry Commoner}
%% \epigraph{We have forgotten how to be good guests, how to walk lightly on the
%% Earth as its other creatures do}{Barbara Ward}
%%% \epigraph{Nuclear power is one hell of way to boil water}{Albert Einstein}
\epigraph{It is the worst of times but it is the best of times because we still have a chance}{Sylvia Earle}
% \epigraph{Generations have trod, have trod, have trod; \\
%     And all is seared with trade; bleared, smeared with toil; \\
%     And wears man's smudge and shares man's smell: the soil \\
% Is bare now, nor can foot feel, being shod. \\
% 
% And for all this, nature is never spent;}{Gerard Manley Hopkins}
%from https://www.poetryfoundation.org/poems/44395/gods-grandeur

% \epigraph{I believe all adults have a moral responsibility to try to protect
% children from climate disruption}{Chris Fox} % from MIT business quotes page.

As noted in section \ref{sec:econ_metab},
the economy is society's metabolism.\index{economic metabolism}
As such, the economy exhibits characteristics of a metabolism\index{economic metabolism}:
it ingests materials and emits wastes\index{waste}.
These characteristics of the economic metabolism\index{economic metabolism} are captured by the
final term in Equation~\ref{eq:IPARX} (repeated below for convenience),
the environmental impacts of resource extraction\index{resource extraction} and consumption~\Xparen{}, 
the topic of this chapter.

\begin{equation} 
  \iparx            \tag{\ref{eq:IPARX}}
\end{equation}

The impact of resources~\Xparen{}
is related to
the types and quantities of resources consumed and the 
ways of processing those resources. 
%Environmental impact intensity is discussed in this chapter.
Resources are the inputs to the economy 
(``food'' in the metabolic analogy), and 
environmental impacts come from the economy's excreted wastes\index{waste}.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Impacts of resources}
\label{sec:impact_intensity}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The impacts of resources~\Xparen{}
is defined as
%
\begin{equation}\label{eq:X}
  \mft{X} \equiv \frac{\textrm{total environmental impacts produced}}{\textrm{total resources extracted}} \; .
\end{equation}
%
Note that ``impacts'' are plural.
Extracting and consuming all the resources necessary to make the economy run 
will have effects on air, water, species diversity, land, and human communities.%
\footnote{
  If you are comfortable with matrix notation, 
  \mft{X} can be thought of as a matrix with
  resources in rows and impacts in columns.  
}
%
Examples of environmental impacts include
water eutrophication\index{eutrophication} (from fertilizer runoff),
SO$_2$\index{sulfur dioxide (SO$_2$)!emissions of} emissions (from burning sulfurous coal\index{coal}),
CO$_2$ emissions (from burning fossil fuels),
desertification\index{desertification}
(due to overcultivation of crops, overgrazing of livestock, and alien species invasion), and
species loss\index{species loss} (due to habitat loss\index{habitat loss},
environmental toxins, and over-exploitation).
With reference to a few of the critical materials in Table~\ref{tab:CRMs},
other examples of environmental impacts caused by resource extraction\index{resource extraction} and consumption include:
%
\begin{itemize}

  \item air, water, and soil pollution\index{pollution!air}\index{pollution!water}\index{pollution!soil}~\cite{Lee:2017ui} 
        in the form of
        bauxite dust,\index{bauxite!dust}
        sulfur dioxide (SO$_2$), and
        nitrous oxides (NO$_\mathrm{x}$) emissions\index{nitrous oxides (NO$_\mathrm{x}$)!emissions of}
        from bauxite mining in Australia;

  \item toxic tailings
        from tungsten\index{tungsten (W)}
        mining operations in Korea~\cite{Lee:2021tz}; and

  \item deforestation\index{deforestation} and
        reduced forest quality~\cite{Kissinger:2020ut}
        to make way for rubber plantations\index{rubber plantations}
        in southeast Asia.

\end{itemize}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Example: carbon intensity of energy}\index{carbon intensity of primary energy}
\label{sec:carbon_intensity_of_energy}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

As discussed in Chapter~\ref{chap:resource_intensity},
our prime example for resource extraction\index{resource extraction} and consumption is energy.
Because CO$_2$ emissions
are a significant source of environmental impact
from energy consumption,
it follows that the prime example of 
environmental impact of resources 
(\;\!\mft{X} in Equation~\ref{eq:IPARX}) is CO$_2$ emissions
in tonnes per MJ of energy provided.
Specifically, the prime example for impact of resources~\Xparen{}
is the CO$_2$ intensity of energy~(\;\!$\mft{X}_{\text{CO}_2}$).
$\mft{X}_{\text{CO}_2}$ is an intensity, because
carbon (numerator) can be considered an input 
to energy derived from fossil fuels (denominator).

Figure~\ref{fig:LLNL_CO2_sankey} is a Sankey diagram
of sources of CO$_2$ emissions from the U.S.\ economy in 2018.
However, in Figure~\ref{fig:LLNL_CO2_sankey}, CO$_2$ emissions
from electricity generation stop at generation and are not attributed to 
electricity purchasers, residential, commercial, and industrial customers.
Table~\ref{tab:corrected_co2_emissions} shows the result of attributing 
CO$_2$ emissions to end uses,
thereby completing the picture of U.S.\ carbon emissions.
Attributing CO$_2$ emissions in this way 
makes it clear that the residential and commercial sectors
are responsible for a larger share of CO$_2$ emissions than 
Figure~\ref{fig:LLNL_CO2_sankey} would otherwise indicate.

\begin{figure}
\centering
\includegraphics[width=\linewidth]{chapters/ch06-ImpactIntensity/figures/Carbon_2018_United-States.png}
\caption[U.S.\ CO$_2$ emissions Sankey diagram]
        {U.S.\ CO$_2$ emissions Sankey diagram\index{Sankey diagram!CO$_2$ emissions} for 2018.
         CO$_2$ emissions from electricity production are not attributed to end uses;
         see Table~\ref{tab:corrected_co2_emissions}.
         Flows in Mt/year.
         \emph{Source}: \citet{Lawrence-Livermore-National-Laboratory:wp}.}
\label{fig:LLNL_CO2_sankey}
\end{figure}


<<US-Carbon-Table, results="asis">>=
US_CO2_by_sector <- readxl::read_excel(file.path("chapters", "ch06-ImpactIntensity", "datasets", "US-Carbon-Emissions.xlsx"),
                                       sheet = "data to plot") %>%
  dplyr::mutate(
    `CO2 share` = `CO2 share` * 100 # To put in % terms.
  ) %>% 
  dplyr::rename(
    `CO$_2$ emissions [Mt]` = `CO2 emissions allocated [million tonnes]`,
    `Proportion [\\%]` = `CO2 share`
  )

print(xtable::xtable(US_CO2_by_sector, digits = c(0, 0, 0, 1),
                     caption = c("U.S.\ CO$_2$ emissions by sector (2018) with
                     CO$_2$ emissions from electricity generation attributed to
                     end uses by
                     fraction of electricity demanded in Figure~\\ref{fig:LLNL_energy_sankey}.", 
                     "U.S.\ CO$_2$ emissions by sector"),
                     label = "tab:corrected_co2_emissions"),
      include.rownames = FALSE,
      include.colnames = TRUE,
      caption.placement = "top",
      type = "latex",
      sanitize.text.function = function(x) {x},
      booktabs = TRUE,
      table.placement = NULL)
@


The yearly rate of world CO$_2$ emitted since 1800 
is shown in Figure~\ref{fig:CarbonEmissionsGraph}.
Annual primary energy consumption\index{primary energy consumption} is shown in Figure~\ref{fig:PrimaryEnergyGraph}.
The ratio of the line in Figure~\ref{fig:CarbonEmissionsGraph} and
the top of Figure~\ref{fig:PrimaryEnergyGraph} 
is the \textbf{carbon intensity of primary energy}\index{carbon intensity of primary energy}~\XCOtwoparen{},
as shown in Figure~\ref{fig:ImpactIntensityGraph}.
The line in Figure~\ref{fig:ImpactIntensityGraph}
demonstrates the long transition
from traditional biofuels\index{traditional biofuel} to fossil fuels
evident in Figure~\ref{fig:PrimaryEnergyGraph}.

<<ImpactIntensityGraph, fig.scap="Carbon intensity of primary energy~\\XCOtwoparen{} vs.\\ time", fig.cap="Carbon intensity of primary energy\\index{carbon intensity of primary energy}~\\XCOtwoparen{}. \\emph{Source}: own calculations. The line represents the ratio of the line in Figure~\\ref{fig:CarbonEmissionsGraph} and the top of Figure~\\ref{fig:PrimaryEnergyGraph} in each year.">>=
carbon_intensity <- dplyr::inner_join(
  CO2_emissions,
  primary_energy %>%
    dplyr::group_by(Year) %>%
    dplyr::summarise(energy_EJ = sum(energy_EJ)),
  by = "Year"
) %>%
  dplyr::mutate(
    CO2_intensity_Mt_per_EJ = CO2_emissions_tonnes / 1e6 / energy_EJ,
  ) 

carbon_intensity %>%
  ggplot2::ggplot(mapping = ggplot2::aes_string(x = "Year", y = "CO2_intensity_Mt_per_EJ")) +
  ggplot2::geom_line(size = data_line_size,
                     colour = data_line_colour, 
                     linetype = data_linetype) +
  ggplot2::labs(x = NULL,
                y = expression("Carbon intensity of energy [Mt "*CO[2]/EJ*"]")) +

  MKHthemes::xy_theme()
@

The biofuel\index{traditional biofuel}-to-fossil-fuel transition has
significant sustainability implications.
Traditional biofuels\index{traditional biofuel} are carbon neutral\index{carbon neutral},
because any CO$_2$ released by combustion was
already sequestered into the biomass as the plants grew.
Fossil fuels are not carbon neutral\index{carbon neutral};
their combustion releases CO$_2$ that was sequestered millions of years ago.
As the world transitioned away from traditional biofuels\index{traditional biofuel} toward fossil fuels,
the carbon intensity of primary energy\index{carbon intensity of primary energy} rose.

On the other hand, use of traditional biofuels\index{traditional biofuel} results in deforestation\index{deforestation}, erosion,
and other negative environmental effects (as well as being inefficient from an
EROI\index{energy return on investment (EROI)}
perspective, as shown in Table~\ref{tab:eroi}).
The transition away from biofuel\index{biofuel} consumption results in cleaner urban air (especially after 
the transition from coal\index{coal} to natural gas\index{natural gas} for residential heating)~\cite{Gordon2016}.
Because having a healthy environment is what economists call a ``normal'' good,
\mft{I} should fall as \mft{A} rises, in general.
In some ways (but not in terms of CO$_2$ emissions and climate change\index{climate change}),
the transition away from traditional biofuels\index{traditional biofuel} did result
in reduced environmental impact.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Reducing the carbon intensity of energy}\index{carbon intensity of primary energy}
\label{sec:reducing_c}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Equation~\ref{eq:IPARX} shows that reducing any of the right-hand side terms to 0
will eliminate CO$_2$ emissions.
That is, if any of 
population~\Pparen{}, 
affluence~\Aparen{},
energy intensity of economic activity (\REp{}, the prime example for \mft{R}),
or
carbon intensity of primary energy\index{carbon intensity of primary energy}
(\;\!\XCOtwo{}, the prime example for \mft{X}\:)
goes to zero,
CO$_2$ emissions will be eliminated.
Few people want to reduce population~\Pparen{} or affluence~\Aparen{}.
The primary energy intensity\index{primary energy intensity}
of the economy~\REpparen{} is declining
(Figure~\ref{fig:EnergyIntensityGraph-Nordhaus}),
but not as fast as population (\mft{P}, Figure~\ref{fig:PopulationGraph}) and
affluence (\mft{A}, Figure~\ref{fig:AffluenceGraph-Nordhaus})
are growing. 
By the process of elimination, 
reducing the carbon intensity of primary energy\index{carbon intensity of primary energy}~\XCOtwoparen{} 
is often considered to be the 
only politically and socially viable way to move in a sustainable direction
with respect to the prime example of energy and CO$_2$ emissions.

Figure~\ref{fig:ImpactIntensityGraph} shows that 
the carbon intensity of primary energy\index{carbon intensity of primary energy}~\XCOtwoparen{}
rose dramatically from 1800--1960, 
as use of fossil fuels came to dominate the world energy story;
see Figure~\ref{fig:PrimaryEnergyGraph}.
Since 1960, the carbon intensity of primary energy\index{carbon intensity of primary energy}
has hovered around 63~MtCO$_2$/EJ.
Thus, for the last 60~years, \XCOtwo{} has been stubbornly constant
and far too high for environmental sustainability\index{environmental sustainability}
(both weak\index{weak sustainability} and strong\index{strong sustainability}).
It appears that eliminating CO$_2$ emissions by significantly reducing
\XCOtwo{} will require unprecedented changes
to the world's primary energy\index{primary energy} supply.
But how?


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Transition to a low-carbon energy regime}
\label{sec:low_carbon_transition}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

There are at least seven often-discussed options for
transitioning to a low carbon energy supply:
(a) carbon capture and storage,
(b) carbon sequestration\index{carbon sequestration},
(c) carbon takeback obligation,
(d) carbon tax,
(e) nuclear electricity,
(e) biomass, and
(f) wind, water, and solar (WWS).
Each option has its own challenges and 
none has yet been implemented on a large enough scale to reduce CO$_2$ emissions;
see Figure~\ref{fig:CarbonEmissionsGraph}.
The subsections below discuss these options and their implementation challenges.


%++++++++++++++++++++++++++++++
\subsection{Carbon capture and storage}
\label{sec:ccs}
%++++++++++++++++++++++++++++++

Carbon capture and storage (CCS)\index{carbon capture and storage (CCS)}
is a way to continue using fossil fuels
during a transition to a low-carbon energy regime. 
In a CCS electricity plant, 
CO$_2$ emissions are captured at the smokestack
and routed underground.
The CO$_2$ is stored, presumably in perpetuity, in caverns or other underground formations.
CCS is not a low-carbon form of energy.
Rather, CCS is a way to avoid carbon emissions from carbon-based energy production.

There are several challenges associated with CCS.
First, it has not been cost-effective.  
Petra Nova\index{Petra Nova}, the only CCS plant in the U.S., disposed of the CO$_2$ it captured
by injecting it into oil fields for enhanced oil recovery.
In 2020, low oil prices made this disposal infeasible, forcing Petra Nova to shut down.
This story illustrates the economic interrelation(s) among primary energy\index{primary energy} sources.
Second, a fossil-fuel power plant fitted with CCS technology 
must ensure that CO$_2$ emissions remain buried. 
If the CO$_2$ escapes to the atmosphere, the effort is ineffective.
Third, there are limited locations with the required underground geological formations 
for CCS.
Finally, CCS is not applicable to CO$_2$ emissions from transportation,
which is the plurality of CO$_2$ emissions; 
see Table~\ref{tab:corrected_co2_emissions}.
It would be impractical to fit every car with a ``CO$_2$ diaper''
to collect CO$_2$ emissions for later injection underground.


%++++++++++++++++++++++++++++++
\subsection{Carbon sequestration}\index{carbon sequestration}
\label{sec:carbon_sequestration}
%++++++++++++++++++++++++++++++

Carbon sequestration\index{carbon sequestration} seeks to extract CO$_2$ from the atmosphere,
storing it in inert form.
One form of carbon sequestration\index{carbon sequestration} is simply planting billions of trees.
A massive, worldwide afforestation effort would be required to extract
the additional carbon that has been added to the atmosphere since the industrial revolution.
In such a scheme, trees consume CO$_2$ and store it in their biomass.
Unfortunately, if the trees are burned or die and decompose, 
the CO$_2$ is returned to the atmosphere.

Alternatively, direct air capture extracts CO$_2$ from the atmosphere,
typically using huge banks of fans and an adsorbent.
Direct air capture is extremely energy intensive because of the heat needed
to regenerate the adsorbents. 
Additional energy consumption for sequestration
lowers the net EROI\index{energy return on investment (EROI)}
of fossil energy production; see Section~\ref{sec:masterE}.
Additionally, because atmospheric CO$_2$ concentrations\index{atmospheric CO$_2$ concentration} are low, massive amounts
of air need to be moved, which makes operating the fans 
both 
monetarily expensive 
and
energy intensive.
Some carbon sequestration\index{carbon sequestration} technologies require expensive and/or rare
materials.
Various schemes have been proposed for how to alleviate some or all of these problems,
but none have been proven to work at scale.

One additional problem with carbon sequestration is selecting the form for 
ultimate storage. 
Geologic storage converts CO$_2$ to liquid form at high pressure and pumps it underground.
Biologic storage is when carbon is trapped in plant matter, soil, or aquatic
environments.
Some have suggested storing CO$_2$ in a stable chemical structure such as graphene.
No consensus has emerged to date.


%++++++++++++++++++++++++++++++
\subsection{Carbon takeback obligation}
\label{sec:ctbo}
%++++++++++++++++++++++++++++++

Another way to reduce CO$_2$ emissions over time is the 
carbon takeback obligation (CTBO)~\cite{Jenkins:2021tg}.\index{carbon takeback obligation (CTBO)}
The CTBO is similar to product takeback policies
which require manufacturers to accept end-of-life product returns from consumers,
thereby keeping wastes\index{waste} (refrigerators, washers, dryers, computers, electronics, and other products)
out of landfills and 
contaminants out of the environment.

The climate change\index{climate change} equivalent of a product takeback is the carbon takeback. 
Under a CTBO, fossil fuel producers and importers would be required 
to permanently sequester the CO$_2$ emitted from the fossil fuels they sell or import.
Industries that emit greenhouse gases (cement making, for example)
would also be required to sequester their emissions.
A CTBO does not specify how the sequestration must occur,
but it specifies who is obliged to perform the sequestration. 
Under a CTBO, fossil fuel producers and other emitting industries
would be free to pass the cost of carbon sequestration\index{carbon sequestration}
to fossil fuel users and other product purchasers (cement buyers, for example),
thereby internalizing the cost of CO$_2$ emissions in the economy.
Consumers would still be free to purchase and use fossil fuels, 
but under a CTBO, the cost of externalities would be evident
in the price. 

A progressive CTBO could be phased over several years.
In the first years, only, say, 10\% of emitted CO$_2$ would need to be sequestered.
A few years later, 20\%.
Then 30\%.
Eventually, fossil fuel producers and other emitting industries
would need to be sequester 100\% of the
greenhouse gases emitted from the use of their product.

There are several implementation challenges for CTBOs.
First, we will need to develop the expertise to 
sequester carbon on a scale never seen before.
(At present, only 0.1\% of emitted carbon in sequestered~\cite[p.~2777]{Jenkins:2021tg}.)
Second, policymakers will need to develop rules and laws for CTBOs, 
and enforcement mechanisms will need to be implemented.
Finally, lower-carbon alternatives will need to be developed for many 
commonplace technologies, including
transport (ground and air), 
building materials (especially cement), and 
building heating and cooling.


%++++++++++++++++++++++++++++++
\subsection{Carbon taxes and offsets}
\label{sec:carbon_tax_offsets}
%++++++++++++++++++++++++++++++

Carbon taxes\index{carbon tax} impose financial penalties on emitters of greenhouse gases.
Emitters pass costs to consumers who face higher prices for goods and services
created with carbon-intensive energy.
Consumers will, over time, prefer lower-cost goods, 
thereby incentivizing manufacturers and service providers
to use low-carbon energy.

Carbon offsets\index{carbon offset} enable carbon emitters to
pay someone else to sequester or reduce carbon emissions.
Carbon emissions are traded as a financial instrument.
A market develops in which emissions and reductions are traded, 
with competition leading to low prices for net emission reductions.
As such, carbon offsets 
enable carbon emitters to shift the responsibility for implementing
emissions reductions.

Both carbon taxes and carbon offsets are 
financial approaches that encourage transitions to a low-carbon energy supply.
Both taxes and offsets nudge consumer and producer behaviors
in the direction of low-carbon energy supply.


%++++++++++++++++++++++++++++++
\subsection{Nuclear electricity}
\label{sec:nuclear_electricity}
%++++++++++++++++++++++++++++++

Nuclear power\index{nuclear energy} (an electricity source only)
may provide a bridge to a sustainable future.
Nuclear power emits little CO$_2$ during plant operation
and has high EROI; see Table~\ref{tab:eroi}. 
However, the energy cost to construct a nuclear power plant 
is higher than other types of
electricity production plants.
In addition, 
it is energy-intensive to mine and refine uranium prior to its use
in a nuclear power plant. 
If the energy required to construct nuclear energy plants
and refine uranium comes from fossil fuels, 
significant CO$_2$ emissions will result from the transition to nuclear electricity.
An additional consideration is the availability of uranium resources,
the topic of \ref{project:nuclear_resources}.


%++++++++++++++++++++++++++++++
\subsection{Biomass}
\label{sec:biomass}
%++++++++++++++++++++++++++++++

In lieu of extracting CO$_2$ from the atmosphere,
we could stop emitting CO$_2$ from fossil fuel combustion in the first place!
One way is to transition away from fossil fuels 
to the energy mix used in the first half of the 19$^{\text{th}}$ century,
namely exclusive use of traditional biofuels\index{traditional biofuel} (wood and wood products)
for heating and electricity;
see Figure~\ref{fig:PrimaryEnergyGraph}.
However, supplying the energy needs of today's economy would be impossible:
we don't have enough available arable land
to grow the required amount of biomass.
(Proof of this statement is left for \ref{project:biofuel_proof}.)
Even if there were enough land, today's methods of growing crops requires
unsustainable energy, water, and chemical inputs;
see Chapter \ref{chap:agriculture}.

Biomass (unmodified wood or wood pellets) 
works well for home heating and cooking
via wood stoves, 
provided that particulate matter\index{particulate matter (PM)} emissions are mitigated appropriately.
However, biomass by itself is not electricity or liquid fuel.
A conversion to biomass for the world's primary energy\index{primary energy} supply would also require 
worldwide replacement of today's fossil fuel electricity generation infrastructure
with a fleet of biomass power plants.
And conversion to biomass would require build-out 
of a biomass-to-liquid-fuels conversion 
infrastructure that does not yet exist.
Finally, conversion to biomass will be accompanied by a reduction 
in EROI\index{energy return on investment (EROI)}; 
see Section~\ref{sec:masterE}.
The EROI\index{energy return on investment (EROI)} for fossil fuels is mostly greater than 20, while
the EROI\index{energy return on investment (EROI)} for corn ethanol\index{corn ethanol}
is typically less than 2~\cite{Hammerschlag:2006uf};
see Table \ref{tab:eroi}.


%++++++++++++++++++++++++++++++
\subsection{Wind, water, and solar electricity}
\label{sec:wws}
%++++++++++++++++++++++++++++++

We could transition the world's energy system
to water (hydro), wind, and solar 
energy sources (WWS)~\cite{Jacobson:2011gc,Delucchi:2011gb}.\index{wind, water, and solar (WWS)}
A transition to WWS would also require 
significant changes to the world's energy infrastructure, 
with at least four large challenges.

First, WWS energy resources produce electricity, not liquid fuels, and 
large changes will be needed.
For example, today's transport sector is almost exclusively powered 
by liquid fossil fuels (gasoline\index{gasoline} and diesel) and illustrates two options for 
transitioning from today's energy system to a WWS energy system.
The first option is to replace
all fossil-fuel vehicles with \textbf{electric vehicles}\index{electric vehicle (EV)},
as is slowly occurring today. 
Electrification of personal vehicles is happening from the top end of the market, 
with expensive offerings from companies such as Tesla\index{Tesla}.
(Electrification has not yet penetrated meaningfully into the freight system,
including trucks, ships, and planes.)
The second option is to use WWS electricity 
in plants that convert biomass feedstocks\index{feedstock} to biofuels\index{biofuel}.

Deployment of a WWS energy system provides a second challenge:
wind and solar are intermittent sources of electricity,
while today's electricity sources 
(coal\index{coal}, natural gas\index{natural gas}, nuclear, and hydro)
are constant.
At present, electric grids accommodate only a fraction 
of intermittent electricity, much less than 100\%.
So a transition to wind and solar primary energy\index{primary energy} sources will require
redesign and reimplementation of electricity grids worldwide
to include electricity storage.

There are several options for grid-scale electricity storage, including
batteries and potential energy storage.
Battery storage will require great quantities of rare earth metals 
and other exotic materials, 
already included on lists of critical raw materials\index{critical raw materials (CRMs)};
see Section~\ref{sec:resources_strong_sustainability}. 
Gravitational potential energy could supply energy storage with nearly 100\% 
round-trip efficiency.
Options for potential energy storage materials include 
water (with a pumped hydro plant)\index{pumped hydro}
or concrete with a system such as Energy Vault~\cite{Energy-Vault:uz}.

A third challenge comes from the water portion of WWS. 
In most areas of the world, 
the potential for expanding the production of hydro electricity is limited.
Most of the Americas, Europe, and Asia are already ``tapped out'' regarding hydropower.
Today, the potential for hydro is greatest in central Africa.
The proposed Grand Inga Dam in the Democratic Republic of the Congo
would be the largest dam in the world and could house a 40--70 GW hydro power station.
Moreover, there are considerable negative environmental and social impacts from 
hydro projects, such as changes to soil salinity, silting, and the destruction
of communities located in the proposed reservoir.

Finally, WWS systems are energy intensive to manufacture.
So the transition to a WWS future will require significant energy investment
in addition to significant financial investment.
If the energy investment to make WWS systems comes from fossil fuels,
significant CO$_2$ will be emitted during the transition
from today's energy regime to a WWS regime.


%++++++++++++++++++++++++++++++
\subsection{Speed of energy transitions}\index{energy transitions}
\label{sec:Etransitions}
%++++++++++++++++++++++++++++++

Figure \ref{fig:ImpactIntensityGraph} shows that a transition to a new form(s)
of energy takes quite a long time to complete. It is costly both in terms of
money and resources, in particular, in terms of energy itself.
It takes energy to make energy-making machines!

Energy historians find that energy transitions often take decades to complete.
Roger Fouquet\index{Fouquet, Roger} has studied energy transitions of the UK in many economic sectors and 
across many energy technologies.
He found that
``since the Industrial Revolution, it took, on average, 
nearly 50 years for energy transitions 
(i.e., the diffusion of energy sources and technologies) 
to unfold''~\cite[p.~6595]{Fouquet:2010tq}.
Given that we have only about a decade before we are committed to 1.5~\degC{} warming
(Section~\ref{sec:GHGCC}), 
50~years is too long.
Large-scale investment to support 
a full-scale transition to a carbon-free energy system 
needs to start yesterday!


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Revisiting the IPARX identity}\index{IPARX identity}
\label{sec:revisit_IPARX}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Chapters~\ref{chap:planetary_boundaries}--\ref{chap:impact_intensity}
show the evolution of all terms in the IPARX identity\index{IPARX identity} (Equation~\ref{eq:IPARX})
over the period 1800--2019
for the prime example of energy consumption and CO$_2$ emissions.
It is instructive to quantify the magnitude and direction of changes 
in the right-side terms for the prime example of energy and CO$_2$ emissions
(\:\!\mft{P}, \mft{A}, \REp{}, and \XCOtwo). 
To do so, we introduce a rate version of the IPARX identity\index{IPARX identity}.

In the rate version of the IPARX identity\index{IPARX identity}, each term is represented 
by an exponential rate of change (\mft{r}\:\!), measured in \%/year.
The rate version of the IPARX identity\index{IPARX identity} indicates 
which terms are moving in a sustainable direction (\mft{r} < 0) and
which terms are moving in an unsustainable direction (\mft{r} > 0).

\begin{equation} \label{eq:IPARX_rate}
  \mft{r}_\mft{I} \approx \mft{r}_\mft{P} + \mft{r}_\mft{A} + \mft{r}_\mft{R} + \mft{r}_\mft{X}
\end{equation}
%
Each rate (\mft{r}\:\!) is calculated by

\begin{equation} \label{eq:rate_calcs}
  \mft{r}_\mft{y} = \left[ \left( \frac{\mft{y}_2}{\mft{y}_1} \right) ^ \frac{\text{1}}{\mft{t}_2 - \mft{t}_1} - \text{1} \right] \times \text{100~\%/year} \; ,
\end{equation}
%
where
\mft{r} is the rate of change in \%/year;
\mft{y} is one of \ICOtwo{}, \mft{P}, \mft{A}, \REp{}, or \XCOtwo{}
for the prime example of energy and CO$_2$ emissions;
subscript ``2'' indicates a later year; and 
subscript ``1'' indicates an earlier year.

<<RatesOfChange>>=
rate_func <- function(df) {
  # Each df has structure
  # t1   y1
  # t2   y2
  yrs <- df[[2,1]] - df[[1,1]]
  # r = (y2/y1)^(1/t2-t1) - 1
  (df[[2,2]]/df[[1,2]])^(1/yrs) - 1
}

rate_to_string <- function(rate, include_units = TRUE) {
  if (include_units) {
    return(paste0(format(round(rate*100, 1), nsmall = 1), "\\%/yr"))
  }
  format(round(rate*100, 1), nsmall = 1)
}

trim_for_chapter <- function(.df, var, years = c(1800, 2019)) {
  .df %>%
    dplyr::filter(Year %in% years) %>% 
    dplyr::select(Year, .data[[var]])
}

impact <- CO2_emissions %>%
  dplyr::select(-Country)
population <- region_pop %>%
  dplyr::filter(Country == "World") %>%
  dplyr::select(Year, total_population)
affluence <- world_gdppc_Nordhaus 
resource_intensity <- energy_intensity %>%
  dplyr::select(Year, primary_energy_type, energy_per_GDP_MJ_per_dollar) %>% 
  dplyr::group_by(Year) %>% 
  dplyr::summarise(energy_per_GDP_MJ_per_dollar = sum(energy_per_GDP_MJ_per_dollar))
carbon_intensity_of_resources <- carbon_intensity %>%
  dplyr::select(Year, CO2_intensity_Mt_per_EJ)

iparx_df <- impact %>% 
  dplyr::full_join(population, by = "Year") %>% 
  dplyr::full_join(affluence, by = "Year") %>% 
  dplyr::full_join(resource_intensity, by = "Year") %>% 
  dplyr::full_join(carbon_intensity_of_resources, by = "Year") %>%
  dplyr::mutate(
    CO2_emissions_tonnes = CO2_emissions_tonnes / 1e9, # convert tonnes to giga-tonnes
    total_population = total_population / 1e9, # convert total population to billions
    gdppc_2017_intl_dollars_per_capita = gdppc_2017_intl_dollars_per_capita / 1000 # convert $/person to k$/person
  ) %>% 
  magrittr::set_names(c("Year", "\\ICOtwo{} [Gt/yr]", "\\mft{P} [billions]", "\\mft{A} [k\\$/person]", 
                        "\\REp{} [MJ/\\$]", "\\XCOtwo{} [Mt/EJ]"))

# Extract the data to be used in the equation
r_I_220 <- iparx_df %>% trim_for_chapter(var = "\\ICOtwo{} [Gt/yr]") %>% rate_func()
r_P_220 <- iparx_df %>% trim_for_chapter(var = "\\mft{P} [billions]") %>% rate_func()
r_A_220 <- iparx_df %>% trim_for_chapter(var = "\\mft{A} [k\\$/person]") %>% rate_func()
r_R_220 <- iparx_df %>% trim_for_chapter(var = "\\REp{} [MJ/\\$]") %>% rate_func()
r_X_220 <- iparx_df %>% trim_for_chapter(var = "\\XCOtwo{} [Mt/EJ]") %>% rate_func()

r_I_20 <- iparx_df %>% trim_for_chapter(var = "\\ICOtwo{} [Gt/yr]", years = c(2000, 2019)) %>% rate_func()
r_P_20 <- iparx_df %>% trim_for_chapter(var = "\\mft{P} [billions]", years = c(2000, 2019)) %>% rate_func()
r_A_20 <- iparx_df %>% trim_for_chapter(var = "\\mft{A} [k\\$/person]", years = c(2000, 2019)) %>% rate_func()
r_R_20 <- iparx_df %>% trim_for_chapter(var = "\\REp{} [MJ/\\$]", years = c(2000, 2019)) %>% rate_func()
r_X_20 <- iparx_df %>% trim_for_chapter(var = "\\XCOtwo{} [Mt/EJ]", years = c(2000, 2019)) %>% rate_func()

# r_I_check should be same as r_I
r_I_check_220 <- r_P_220 + r_A_220 + r_R_220 + r_X_220
r_I_check_20 <- r_P_20 + r_A_20 + r_R_20 + r_X_20

stopifnot(abs(r_I_check_220 - r_I_220) < 0.0005)
stopifnot(abs(r_I_check_20 - r_I_20) < 0.0005)
@


Select data from Figures~\ref{fig:CarbonEmissionsGraph},
\ref{fig:PopulationGraph}, 
\ref{fig:AffluenceGraph-Nordhaus}, 
\ref{fig:EnergyIntensityGraph-Nordhaus}, 
and~\ref{fig:ImpactIntensityGraph} 
are shown in Table~\ref{tab:iparx_select_years}.
Data from Table~\ref{tab:iparx_select_years}
can be used with Equation~\ref{eq:rate_calcs}
to answer the question, 
``what equivalent annual rate of change (\mft{r}\:\!) 
would give the same start and end points
in 1800 and 2019 
or
2000 and 2019?''
The answers are shown in Equation~\ref{eq:IPARX_rate_with_numbers}.

<<IPARX_Table, results="asis">>=
years_for_rate_table <- c(1800, 1850, 1900, 1950, 1970, 2000, 2010, 2019)

print(xtable::xtable(iparx_df %>% 
                       dplyr::filter(Year %in% years_for_rate_table), digits = c(0, 0, 3, 2, 2, 2, 2),
                     caption = c("Values of IPARX identity\\index{IPARX identity} terms for selected years in Figures~\\ref{fig:CarbonEmissionsGraph}, \\ref{fig:PopulationGraph}, \\ref{fig:AffluenceGraph-Nordhaus}, \\ref{fig:EnergyIntensityGraph-Nordhaus}, and~\\ref{fig:ImpactIntensityGraph}. With Equation~\\ref{eq:IPARX_rate_with_numbers}, these data allow us to see whether the world is becoming more sustainable or less sustainable over time and why; see \\ref{project:iparx_calcs}.", "Values of IPARX terms for selected years"),
                     label = "tab:iparx_select_years"),
      include.rownames = FALSE,
      include.colnames = TRUE,
      caption.placement = "top",
      type = "latex",
      sanitize.text.function = function(x) {x},
      booktabs = TRUE,
      table.placement = NULL)
@


\begin{equation}
\label{eq:IPARX_rate_with_numbers}
\footnotesize
\begin{tabular}{rccccccccc}
     & \rateICOtwo{} & $\approx$ & \rateP{}   & $+$ & \rateA{}   &   $+$ & \rateREp{}  & $+$ & \rateXCOtwo{} \\[6pt]
1800--2019 & \Sexpr{rate_to_string(r_I_220)} & $\approx$ & \Sexpr{rate_to_string(r_P_220)} & $+$ & \Sexpr{rate_to_string(r_A_220)} &
                                    $-$ & \Sexpr{rate_to_string(abs(r_R_220))} & $+$ & \Sexpr{rate_to_string(r_X_220)}   \\
2000--2019 & \Sexpr{rate_to_string(r_I_20)} & $\approx$ & \Sexpr{rate_to_string(r_P_20)} & $+$ & \Sexpr{rate_to_string(r_A_20)} &
                                    $-$ & \Sexpr{rate_to_string(abs(r_R_20))} & $+$ & \Sexpr{rate_to_string(r_X_20)}   \\
\end{tabular}
\normalsize
\end{equation}

Equation~\ref{eq:IPARX_rate_with_numbers} shows that carbon emissions 
(Figure~\ref{fig:CarbonEmissionsGraph})
are increasing 
% at an average rate of $\mft{r}_\mft{I} =$ \Sexpr{rate_to_string(r_I_220)}
at an average rate of \rateICOtwo{}~=~\Sexpr{rate_to_string(r_I_220)}
since pre-industrial times (1800--2019)
and \rateICOtwo{}~=~\Sexpr{rate_to_string(r_I_20)}
over the last two decades (2000--2019). 
(Equation~\ref{eq:IPARX_rate_with_numbers} and 
the data in Table~\ref{tab:iparx_select_years}
can be used to discern
trends over other periods of time. 
See \ref{project:iparx_calcs}.)
The declining energy intensity of economic activity~(\rateREp{} < 0)
is the only term in the IPARX identity\index{IPARX identity}
putting downward pressure on the CO$_2$ emissions growth rate (\rateICOtwo{}).
All other terms on the right side of Equation~\ref{eq:IPARX_rate_with_numbers}
are greater than zero and are driving CO$_2$ emissions upward.
Interestingly, the rate of change of the impact intensity 
of primary energy consumption\index{primary energy consumption} (\rateXCOtwo{})
is smaller (\Sexpr{rate_to_string(r_X_20)})
in the past two decades than over the past two centuries
(\Sexpr{rate_to_string(r_X_220)}), because 
the world's transition to a fully carbonized energy system
was largely complete by 1970;
see Figure~\ref{fig:ImpactIntensityGraph}.
The beneficial effect of the declining resource intensity of the economy (\rateREp{}~<~0)
is growing over time 
(\rateREp{}$~=~-$\Sexpr{rate_to_string(abs(r_R_220))} for 1800--2019 and
\rateREp{}$~=~-$\Sexpr{rate_to_string(abs(r_R_20))} for 2000--2019).

%^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
\begin{mcframe}[0.90\textwidth](0.85\textwidth)
%^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The positive terms in Equation~\ref{eq:IPARX_rate_with_numbers}
represent sources of some of our sustainability challenges\index{sustainability challenges}:
rising population (\rateP{}~>~0), 
rising affluence (\rateA{}~>~0), and 
expanded use of fossil fuels (\rateXCOtwo{}~>~0).

\end{mcframe}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{IPARX interactions}
\label{sec:iparx_interactions}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The IPARX identity\index{IPARX identity}
appears to be a straight multiplication of independent terms
(\:\!\mft{P}, \mft{A}, \mft{R}, and \mft{X}\:).
But it is not.
There are interactions among the terms that deserve attention.
We note four such interactions below.
The interactions among IPARX identity\index{IPARX identity} terms
are an example of the interconnected character of human society as we know it.
Indeed, policies directed at improving one term of the IPARX identity\index{IPARX identity}
will always have effects (intentional and unintentional)
on other terms of the IPARX identity\index{IPARX identity}.

%^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
\begin{mcframe}[0.90\textwidth](0.85\textwidth)
%^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Former U.S.\ representative Vernon Ehlers'\index{Ehlers, Vernon}
many years in education and government led him to quip frequently
``you can never do only one thing.''

\end{mcframe}


%++++++++++++++++++++++++++++++
\subsection{The rebound effect}\index{rebound effect}
\label{sec:rebound_effect}
%++++++++++++++++++++++++++++++

Energy efficiency\index{energy efficiency} is widely seen as a means of reducing CO$_2$ emissions.
The thinking goes that either the resource intensity (\:\!\REp{} in the IPARX identity\index{IPARX identity}, 
Equation~\ref{eq:IPARX}) 
or impact intensity~\XCOtwoparen{}, or both,
will go down as efficiency rises.
However, energy efficiency\index{energy efficiency} is known to stimulate economic activity 
by a mechanism called the \textbf{rebound effect}\index{rebound effect}~\cite{Brockway:2021ww},
wherein monetary savings (from reduced energy consumption at a newly-efficient device)
are reinvested, leading to economic growth.
Economic growth raises the GDP of an economy,
so affluence~\Aparen{} will increase.
As \mft{A} increases, energy consumption will increase.
Whether energy efficiency\index{energy efficiency} actually saves energy and actually reduces CO$_2$ emissions
depends on the strength of the rebound effect\index{rebound effect}.
When rebound effects\index{rebound effect} are so large as to wipe out the initial energy savings,
\textbf{backfire}\index{backfire} is said to occur~\cite{Sorrell:2009cg,Sorrell:2010ul}.
Backfire\index{backfire} is a threat to a low-carbon future~\cite{Brockway:2017a}.
Thus, we must be careful about crafting policies to address 
the \REp{} or \XCOtwo terms in the IPARX identity\index{IPARX identity}.
We may inadvertently affect \mft{A} with the consequence of undoing 
the good we intended.


%++++++++++++++++++++++++++++++
\subsection{Affluence and population}
\label{sec:affluence_and_population_interaction}
%++++++++++++++++++++++++++++++

As discussed in Chapter~\ref{chap:population}, 
population depends on many factors. 
(For one example of the dependencies of population, 
see the causal loop diagram from the World3 model\index{World3}
shown in Figure~\ref{fig:World3loops}.)
One clear trend from history is that increasing affluence~(\rateA{}~>~0)
leads to reduced population growth rate~(\rateP~<~0).
Thus, the affluence and population terms of the IPARX identity\index{IPARX identity}
are not independent.


%++++++++++++++++++++++++++++++
\subsection{GDP and energy}
\label{sec:gdp_and_energy_interaction}
%++++++++++++++++++++++++++++++

The relationship between energy consumption and GDP
exposes another interaction among the IPARX identity\index{IPARX identity} terms
for the primary example of energy consumption and CO$_2$ emissions.
Historically, as GDP (equal to $\mft{P} \times \mft{A}$ in Equation~\ref{eq:IPARX}) increases, 
primary energy consumption\index{primary energy consumption} also rises,
as shown in Figure~\ref{fig:E_vs_GDP_graph}.

<<E_vs_GDP_graph, fig.scap="World primary energy consumption vs.\\ world GDP", fig.cap = "World primary energy consumption\\index{primary energy consumption} vs.\\ world GDP.">>=
egdp_df <- primary_energy %>% 
  dplyr::group_by(Year) %>%
  dplyr::summarise(energy_EJ = sum(energy_EJ)) %>%
  dplyr::left_join(world_gdp_Nordhaus, by = "Year") %>%
  dplyr::mutate(
    gdp_trillions = world_gdp_2017_intl_dollars / 1e12
  )

egdp_df %>%
  ggplot2::ggplot(mapping = ggplot2::aes(x = gdp_trillions, y = energy_EJ)) +
  ggplot2::geom_line(size = data_line_size, 
                     colour = data_line_colour,
                     linetype = data_linetype) + 
  ggplot2::labs(x = "GDP [trillion 2017 Intl. $]", 
                y = "Primary energy consumption [EJ]") +
  
  MKHthemes::xy_theme()
@


However, the concave downward nature of Figure~\ref{fig:E_vs_GDP_graph} indicates that
each additional dollar of GDP requires incrementally less energy consumption
than the dollar before.
The line in Figure~\ref{fig:E_vs_GDP_graph} is concave downward because
the primary energy intensity\index{primary energy intensity} of the economy ($\mft{R}_{\!\mft{Ep}}$)
has been decreasing over time,
as shown in Figure~\ref{fig:EnergyIntensityGraph-Nordhaus}.
Thus, as GPD ($\mft{P} \times \mft{A}$\:\!) rises, 
the primary energy intensity\index{primary energy intensity} of economic activity
(\:\!\REp{} in the IPARX identity\index{IPARX identity} for the prime example) 
is expected to fall, 
as it has been for 220 years.
(Recall from Section~\ref{sec:energy_intensity_of_the_economy}, 
however, that \REp{} is falling over time primarily because
per-dollar consumption of sustainable biomass is falling over time.
Ironically, unsustainable fossil fuel consumption is more constant 
than sustainable biomass consumption over time, per dollar of GDP;
see Figure~\ref{fig:per_gdp_material_use}.)

\REp{} is a type of economic intensity
that represents the effectiveness of using energy to make GDP.
This fact raises an interesting question:
can we use improved economic effectiveness 
(decreasing \REp{},
brought about by rising energy efficiency\index{energy efficiency})
to reduce environmental impacts (\:\!\mft{I} in Equation~\ref{eq:IPARX}), 
CO$_2$ emissions being the prime example)?
It certainly helps, as decreasing \REp{}
puts downward pressure on \ICOtwo{} in Equation~\ref{eq:IPARX}.
However, recent research indicates that rising energy efficiency\index{energy efficiency}
(and declining~\REp{})
has never reduced energy consumption or environmental impacts, 
at least at the worldwide level~\cite{Brockway:2021ww}.
The rebound effect\index{rebound effect} is thought to be a strong candidate
for the reason why efficiency has not led to decreases
in energy consumption and CO$_2$ emissions over time;
see Section~\ref{sec:rebound_effect}.
Indeed, a circular trap exists.
Energy efficiency\index{energy efficiency} is known to stimulate economic growth, and 
increased economic activity leads to more energy consumption.
Because of interactions between energy and the economy, 
it is hard to see how energy efficiency\index{energy efficiency} alone 
leads to reduced energy consumption and CO$_2$ emissions.
We have never decoupled energy consumption from economic activity
at the world level at any point in history.
So long as energy consumption generates CO$_2$ emissions, 
energy efficiency\index{energy efficiency}
alone will be unlikely to decouple environmental impacts
from economic activity.

Economic growth, per-se, is not problematic.
However, when 
(a)~economic activity requires energy 
and
(b)~energy consumption causes CO$_2$ to be emitted,
economic growth leads to sustainability challenges\index{sustainability challenges!economic growth}.
Reducing the carbon intensity of primary energy\index{carbon intensity of primary energy} 
(\;\!\XCOtwo{}the prime example for \mft{X} in Equation~\ref{eq:IPARX})
is one way to limit the environmental impacts of economic activity.
Interactions associated with a transition to low-carbon energy supplies
are the topic of the next section.


%++++++++++++++++++++++++++++++
\subsection{Renewables}
\label{sec:renewables_interaction}
%++++++++++++++++++++++++++++++

The transition to renewable energy sources 
is expected to reduce the CO$_2$ intensity of energy consumption
(\;\!\XCOtwo{} in the prime example), 
if the CO$_2$ avoided by renewable generation over the lifetime of a renewable device
(say, a photovoltaic solar panel\index{solar panel})
is less than the CO$_2$ embodied
in the renewable device. 
That said, many advocates of Green Growth, a Green New Deal, and similar public policies 
promote the idea that a transition to green infrastructure, including renewable energy,
will stimulate economic growth and increase affluence.
If they are right, 
a renewables-driven decrease in \XCOtwo{} would lead to an increase in \mft{A}
in the IPARX identity\index{IPARX identity} (Equation~\ref{eq:IPARX}).
The strength of each effect (\;\!\XCOtwo{} $\downarrow$, $A \uparrow$) 
will determine whether Green Growth or a Green New Deal will actually decrease 
environmental impacts~\Iparen{} or CO$_2$ emissions (\;\!\XCOtwo{} in the prime example).


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Summary}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The impact of resources~\Xparen{}
represents the environmental impacts of extracting and consuming natural resources
in Equation~\ref{eq:IPARX}.
For the prime example of energy and CO$_2$ emissions, 
the carbon intensity of primary energy\index{carbon intensity of primary energy}~\XCOtwoparen{} 
quantifies the CO$_2$ emissions from consuming energy.
\XCOtwo{} grew with the transition from biofuels to fossil fuels
but leveled off in the last few decades.
Revisiting the IPARX identity\index{IPARX identity},
we see that rising population~\Pparen{}\index{sustainability challenges!population}, 
rising affluence~\Aparen{}\index{sustainability challenges!affluence}, and
expanded use of fossil fuels\index{sustainability challenges!fossil fuels}~\XCOtwoparen{}
are the sources of our sustainability challenges.

The IPARX identity and 
the prime example (energy consumption and CO$_2$ emissions)
show that we are heading in an unsustainable direction,
because CO$_2$ emissions are growing over time.
In other words,
Part~\ref{part:IPARX} (Chapters~\ref{chap:planetary_boundaries}--\ref{chap:impact_intensity})
has described the \emph{what} of our sustainability challenges.
Next, Part~\ref{part:sustainability_challenges}
(Chapters~\ref{chap:households}--\ref{chap:land_use_urban_planning})
explores reasons \emph{why} we face these challenges
in several sectors of the economy.
Finally, Part~\ref{part:actions}
(Chapters~\ref{chap:government} and~\ref{chap:personal_action})
provides suggestions for \emph{how} to respond, 
collectively and individually.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Further Reading}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Daniel Yergin, \emph{The new map: Energy, climate, and the clash of nations}.
London: Penguin, 2020. \\

\noindent Edward Humes, \emph{Garbology: Our dirty love affair with trash}. New York: Avery, 2012.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{See Also}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Energy Vault simulation:  \\ \url{https://www.vimeo.com/335818817}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Questions}
\markright{Questions}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{questions}

\item Do renewable energy sources have ``emissions?'' If so, what are they?
        Make reference to Equation~\ref{eq:IPARX}. At a minimum, discuss
        solar photovoltaic\index{solar panel}, wind turbines, hydro power, and renewable biofuels.

\item Fossil fuels have environmental impacts other than CO$_2$. 
      One example is oil spills,
      such as the Exxon Valdez\index{Exxon Valdez} and the Deep Water Horizon\index{Deep Water Horizon} disasters.
      (The International Tanker Owners Pollution Federation\index{International Tanker Owners Pollution Federation}
      reports ``only'' 18 oil
      spills larger than 700 tonnes for the period 2010--2019 versus 245 in the 1970s.) 
      Other examples include environmental impacts from hydraulic fracking\index{hydraulic fracking}
      fluids; air quality issues associated with burning fossil fuels such as
      soot, smog\index{smog}, and ozone\index{ozone}; and soil contamination from leaking underground 
      fuel-storage tanks.
      There is a tendency to approach each of these impacts
      as a separate problem and to invent technological fixes specific to each 
      problem, which is often a successful approach. 
      Indeed, the rate of oil spills is down due to better technology. 
      However, these technological solutions come with their own costs, risks, 
      and inherent tradeoffs.
      Give some examples of the tradeoffs inherent in pollution prevention\index{pollution!prevention} 
      technologies.
      How do we manage tradeoffs among different types of solutions?
      
\item Energy historian Roger Fouquet\index{Fouquet, Roger} found that it has taken, historically, on average, 50 years
      to transition from one energy source to another~\cite[p.~6595]{Fouquet:2010tq}.
      At this moment in time, it is unlikely that humanity has 50 years
      to effect a transition to renewable sources of energy
      to avoid irreversible effects of climate change\index{climate change}.
      What should we do?
      Give up on mitigation and focus on adaptation?
      Find a way to do better than the 50-year average duration for an energy transition?
      If so, what are those ways? 
       
\item Expanding on the issues raised in the previous questions, 
      nuclear power has had its own environmental issues. 
      Disasters such Fukushima Daiichi\index{Fukushima Daiichi},
      Three-Mile Island\index{Three-Mile Island}, and 
      Chernobyl\index{Chernobyl} come to mind. 
      High-level nuclear waste\index{waste!nuclear} is another. 
      On the other hand, coal-fired power plants\index{coal-fired power plant}
      in the Midwest region have emitted 
      enough mercury that fish in the Great Lakes\index{Great Lakes} are not safe for consumption
      by children or women of child-bearing age. 
      How do you make decisions about trading off different types of 
      environmental impacts?
      Which impacts are more acceptable? Which are less acceptable?
      
\item The naive tendency is to read the previous three questions and just say that
      all impacts are bad, which is true by definition of the word ``impact''
      but it is not helpful. The more interesting and helpful question is the 
      debate between a cost/benefit perspective (do the benefits provided by this
      form of energy outweigh the costs?) and a sustainability perspective
      (``is this form of energy sustainable and, if so, for how long?'').
      Do you lean more to the  cost/benefit perspective or the sustainability 
      perspective and why? 
      Are you using a weak\index{weak sustainability} or strong sustainability\index{strong sustainability} criterion?
      
\item Some people object to wind turbines\index{wind turbine} because they kill birds. 
      The truth is, all human structures kill birds. 
      What are the alternatives (to having wind turbines at all)?
      What is the cost/benefit analysis of having wind turbines\index{wind turbines}?
      Who does the analysis and makes the decisions about whether to have wind
      turbines and where to site them?
      Do birds get a voice in the decision? Should they?
      If so, who speaks for the birds?
      What about other animals, say clams or ants? 
      What about trees or the wind itself?
      What would your assumptions have to be to answer yes to any of these questions?

\item Which would you prefer, a biomass energy system or a water-wind-solar (WWS)
      energy system? Why?

\item What would be the consequences of a reduction in EROI\index{energy return on investment (EROI)}
      that would accompany 
      a conversion to a biofuel-based energy system?
      Make reference to the earlier years of 
      Figures~\ref{fig:PopulationGraph}, 
      \ref{fig:AffluenceGraph-Nordhaus}, 
      \ref{fig:EnergyIntensityGraph-Nordhaus}, 
      \ref{fig:ImpactIntensityGraph}.
        
\item One issue with a fully WWS electricity grid is the supposed need for significant
      energy storage. 
      Is grid-scale storage really required or is it just something we would like 
      to have? 
      How can you tell?

\item Consider the energy transition shown in Figure \ref{fig:ImpactIntensityGraph}.
      What does Figure \ref{fig:ImpactIntensityGraph} indicate about the length
      of time needed to transition to global carbon-free energy?
      Why did we go from a low-carbon economy (such as in 1800) to the high-carbon
      economy we have today? 
      Hint: see Table~\ref{tab:eroi}.

\item Should the transition to renewable energy sources be actively managed 
      (for example by government policy) or should we let the ``invisible hand
      of the market'' manage the transition for us? Why?
      Are your reasons strictly because of the outcome(s) you imagine? 
      What assumptions are you making that lead to those outcomes?
      Or do you have philosophical reasons to prefer active versus passive 
      management?
      Who is actually making the decisions about transitions to renewable energy
      (or not)?

\item Find the proportion of renewable energy in the world's energy mix today.
      Does this proportion indicate that we are far into the transition to a 
      low-carbon energy regime?

\item Argue for and against making Table~\ref{tab:corrected_co2_emissions}.
      What does Table~\ref{tab:corrected_co2_emissions} show that
      Figure~\ref{fig:LLNL_CO2_sankey} does not (and vice versa)?
      Which do you find more helpful? Why?
      What sorts of decisions is each most helpful with?
      
\item Do you agree with the process of elimination in Section~\ref{sec:reducing_c}?
      Are there other approach(es)? If so, what are they?
      What assumptions lead you to prefer one approach over another?

\item Should carbon capture and storage/sequestration be pursued as a stop-gap
      measure (until we get fully renewable energy)?
      What is your criteria for making that decision?
      Under what circumstances would your answer change?
      
\item The big issue for carbon capture and storage/sequestration (CCS) is who are the 
      stakeholders---who pays and who benefits?
      ``It's too expensive'' is just another way of saying ``we don't value that
      very much.'' Are there legal or financial arrangements that could be made 
      that would sufficiently incentivize CCS such that it would be profitable?
      If so, why hasn't this been done already?

\end{questions}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Projects}
\markright{Projects}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{projects}

  \item \label{project:biofuel_proof}
        Investigate the energy available in a hectare of biomass production.
        How many hectares of biomass would need to be harvested annually
        to supply today's energy needs?
        How much available arable land exists in the world?
        What fraction of available arable land would be required to transition
        to a biomass-based energy system? 
        
  \item Research the potential for CO$_2$ storage in graphene\index{graphene}. 
        What are the energy requirements for such a scheme?
        How many additional solar panels\index{solar panel} would be needed to 
        convert a ton of CO$_2$ to graphene?
        
  \item Research the Petra Nova\index{Petra Nova} 
        carbon capture and storage (CCS)\index{carbon capture and storage (CCS)} plant.
        What is the feasibility of replicating the Petra Nova scheme
        to all fossil fuel electricity power plants in the U.S.?
        In the World?
        What has been the cost to implement the Petra Nova plant?
        Who paid that cost?
        If the Petra Nova plant can't be replicated to all power plants, 
        are there other feasible options for CCS?

  \item Electrification of the world's transportation system is likely to be a costly endeavor.
        Find the number of petroleum\index{petroleum}-powered cars in service today. 
        Find a typical cost of an electric car today. 
        What is an estimated cost of electrifying the vehicle fleet?
        What fraction of world GDP does this cost represent?
      
  \item Research the countries with the largest fractions of intermittent 
        electricity generation (wind and solar).
        What features of those countries allow large fractions of 
        intermittent generation? 
        What would happen to the electricity grid in those countries 
        if the fraction of intermittent generation went to 100\%?
        
  \item Research and rank the EROI\index{energy return on investment (EROI)} 
        of many primary energy\index{primary energy} sources, 
        including fossil fuels and renewables such as biofuels.
        What does your ranking imply for transitions to a low-carbon energy regime?
        Critique how your sources drew the boundaries
        around which they calculated EROI\index{energy return on investment (EROI)}.
        Compare your results to Table~\ref{tab:eroi}.
        
  \item What would have to be true for the world to be able to implement a 100\% WWS energy system?
        
  \item It has been argued that the transition to a low-carbon energy regime
        is a \textbf{grand challenge}\index{grand challenge} that will require funding levels 
        that rival the Apollo program, President Johnson's ``Great Society'' initiatives,
        and President Reagan's ``Star Wars'' program~\cite{Heun:2008vu}.
        Find several updated estimates of the costs for these and other large 
        government programs.
        Compare to cost estimates to effect a transition to a low-carbon energy regime.
        
  \item Calculate land required to convert all energy production to solar sources
        in the U.S. 
        What effect would a fully-solar energy infrastructure have on natural landscape?
        Where would you locate the solar panels\index{solar panel}?
        What transmission issues would emerge?
  
  \item What are the other resource implications of a transition to WWS energy sources? 
        For example, do we have enough neodymium (Nd)\index{neodymium (Nd)} for the wind turbines
        required to implement a WWS energy supply? 
        
  \item Derive Equation~\ref{eq:IPARX_rate} from Equation~\ref{eq:IPARX}.
        You will use (1 + r$_\text{1}$)(1 + r$_\text{2}$) 
        $\approx$ r$_\text{1}$ + r$_\text{2}$ + 1 
        when \mft{r}$_\text{1}$ <\!\!< 1 and \mft{r}$_\text{2}$ <\!\!< 1
        in the derivation.
  
  \item \label{project:iparx_calcs}
        Verify the calculations in Equation~\ref{eq:IPARX_rate_with_numbers}
        using data from Table~\ref{tab:iparx_select_years}.
        Then recalculate the terms in Equation~\ref{eq:IPARX_rate_with_numbers} 
        for the last 69 years only (1950--2019), 
        for the last 49 years only (1970--2019), and
        for the last 9 years only (2010--2019).
        How are the results similar to or different from the results 
        shown in Equation~\ref{eq:IPARX_rate_with_numbers}? 
        
  \item After many years of studying energy-economy interactions and the rebound effect\index{rebound effect}, 
        \citet{Sorrell:2010ul}\index{Sorrell, Steve} advanced five controversial propositions:
        % 
        \begin{enumerate} [label=(\arabic*)]

          \item the rebound effects\index{rebound effect}
                from energy efficiency\index{energy efficiency} improvements are significant 
                and limit the potential for decoupling energy consumption from economic growth; 

          \item the contribution of energy to productivity improvements and economic growth 
                has been greatly underestimated;
        
          \item the pursuit of improved efficiency needs to be complemented by an ethic of sufficiency;
  
          \item sustainability is incompatible with continued economic growth in rich countries; and 
  
          \item a zero-growth economy\index{steady-state economy} is incompatible with a fractional reserve banking system.

        \end{enumerate}

        Sorrell's propositions suggest that 
        interactions between energy and the economy are so pervasive that
        a deep rethinking of the structure of society is warranted
        if we are to address, in a meaningful way, 
        the sustainability challenges\index{sustainability challenges} that we face.
        Read Sorrell's paper and write a report that evaluates 
        the five propositions.
        Compare and contrast the five propositions with prevailing cultural norms in your society.
        Assess the necessity, desirability, and feasibility of reconfiguring society 
        as suggested in the article.
        
  \item At the end of Chapter~\ref{chap:impact_intensity}, you have learned about all four 
        right-side terms of the IPARX identity\index{IPARX identity} (Equation~\ref{eq:IPARX}).
        Write a paper that discusses each term and suggests your favored policy 
        to reduce the magnitude of each term. 
        Next look into the
        \href{https://www.climateinteractive.org/tools/en-roads/}{EnROADS climate change solutions simulator}\index{EnROADS}
        and find its policy options for addressing climate change\index{climate change}. 
        Which of your favored policies appears in the EnROADS options?
        Now choose a suite of policies in EnROADS that includes as many of your favored policies as possible.
        Can you achieve less than 1.5~\degC{} of warming?
        In the paper, describe the suite of policies you chose
        and consider their technical and political feasibilities.
        
  \item \label{project:nuclear_resources}
        Research the availability of uranium\index{uranium} resources. 
        What are the reserves?
        Is our current consumption rate weakly sustainable\index{weak sustainability}?
        What is the maximum fraction of world electricity usage that could be powered
        by nuclear and still be weakly sustainable?
        What if ``energy usage'' replaced ``electricity usage?''
        
        Research the availability of thorium resources and the use of thorium as
        a nuclear fuel. 
        Repeat the uranium analysis above for thorium.
        
  \item Research the source(s) of ocean plastic pollution.  
        What are the effects of ocean plastics on human health and communities?
        Is plastic in the oceans a single problem or several?
        \label{project:ocean_plastic}
        
  \item Section~\ref{sec:rebound_effect} discusses the rebound effect\index{rebound effect},
        wherein monetary savings from energy efficiency\index{energy efficiency} are spent elsewhere in the economy,
        raising energy consumption in other sectors.
        Green revolving funds~(GRFs) are thought to be a way to mitigate the rebound effect\index{rebound effect}.
        A green revolving fund is the repository for 
        monetary savings from energy efficiency\index{energy efficiency}.
        Green revolving fund assets must be invested in further energy efficiency\index{energy efficiency},
        thereby preventing ``leakage'' of the benefits 
        (reduced energy consumption and CO$_2$ emissions)
        of energy efficiency\index{energy efficiency}.
        Research green revolving funds. 
        Where have they been successful to reduce energy consumption and carbon emissions?
        Where have they failed?
        What are the factors that make GRFs successful?
        Conversely, what factors lead to failure?
        Investigate implementing a green revolving fund at your 
        school, place of employment, or local government.
        What would it take to establish a GRF?
        What are the roadblocks?
        Who would benefit from a GRF and why?
        Can the beneficiaries be partners in advocating for a GRF?

\end{projects}



\cleardoublepage

