% The next command tells RStudio to do "Compile PDF" on book.Rnw,
% instead of this chapter, thereby eliminating the need to switch back to book.Rnw 
% before making the book.
%!TEX root = ../../book.Rnw


%#############################################################
\chapter{Impact intensity of resources~\Xparen{}}
\label{chap:impact_intensity}
%#############################################################
% \epigraph{Normal human activity is worse for nature than the biggest 
% nuclear accident in history.}{Martin Cruz Smith}
%\epigraph{Environmental pollution is an incurable disease. It can only
%be prevented.}{Barry Commoner}
%% \epigraph{We have forgotten how to be good guests, how to walk lightly on the
%% Earth as its other creatures do}{Barbara Ward}
%%% \epigraph{Nuclear power is one hell of way to boil water}{Albert Einstein}
\epigraph{It is the worst of times but it is the best of times because we still have a chance}{Sylvia Earle}
% \epigraph{Generations have trod, have trod, have trod; \\
%     And all is seared with trade; bleared, smeared with toil; \\
%     And wears man's smudge and shares man's smell: the soil \\
% Is bare now, nor can foot feel, being shod. \\
% 
% And for all this, nature is never spent;}{Gerard Manley Hopkins}
%from https://www.poetryfoundation.org/poems/44395/gods-grandeur

% \epigraph{I believe all adults have a moral responsibility to try to protect
% children from climate disruption}{Chris Fox} % from MIT business quotes page.

As noted in section \ref{sec:econ_metab},
the economy is society's metabolism.\index{economy!as society's metabolism}
As such, the economy exhibits characteristics of a metabolism:
it ingests materials and emits wastes.
These characteristics of the economic metabolism are captured by the
final term in Equation~\ref{eq:IPARX} (repeated below for convenience),
the environmental \emph{impact intensity} of resource extraction and consumption~\Xparen{}, 
the topic of this chapter.

\begin{equation} 
  \iparx            \tag{\ref{eq:IPARX}}
\end{equation}

The impact intensity of resources~\Xparen{}
is a function of \mft{R} (resource extraction and consumption) discussed in 
Chapter~\ref{chap:resource_intensity}, in that the 
type and intensity of environmental impacts are directly related to 
the types, quantities, and ways of processing resources. 
%Environmental impact intensity is discussed in this chapter.
\mft{R} represents the inputs to the economy 
(``food'' in the metabolic analogy), and 
\mft{X} represents the economy's excreted wastes.
% We say ``represents'' and not ``is'' because both terms are \emph{normalized} to
% a single dollar of GDP.

\mft{X} is defined as
%
\begin{equation}\label{eq:X}
  \mft{X} = \frac{\textrm{total environmental impacts produced}}{\textrm{total resources extracted}} \; .
\end{equation}
%
Note that ``impacts'' are plural.
Extracting and consuming all the resources necessary to make the economy run 
will have effects on air, water, species diversity, land, and human communities.
(If you are comfortable with matrix notation, \mft{X} can be though of as a matrix with
impacts in columns and resources in rows.)


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Impact intensity of resource extraction}
\label{sec:impact_intensity}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The impact intensity of resource extraction and consumption~\Xparen{}
represents the amount of environmental impact (emitted wastes)
per unit of extracted and consumed resources (ingested materials).
Examples of environmental impacts include
water eutrophication\index{eutrophication} (from fertilizer runoff),
SO$_2$\index{sulfur dioxide (SO$_2$)!emissions of} emissions (from burning sulfurous coal),
CO$_2$ emissions\index{carbon dioxide (CO$_2$)!emissions of} (from burning fossil fuels),
desertification\index{desertification}
(due to overcultivation of crops, overgrazing of livestock, and alien species invasion), and
species loss\index{species loss} (due to habitat loss, environmental toxins, and over-exploitation).
With reference to a few of the critical materials in Table~\ref{tab:CRMs},
specific examples of environmental impacts caused by resource extraction include:
%
\begin{itemize}

  \item Air, water, and soil pollution~\cite{Lee:2017ui} in the form of
        bauxite dust,\index{bauxite!dust}
        sulfur dioxide (SO$_2$), and
        nitrous oxides (NO$_\mathrm{x}$) emissions\index{nitrous oxides (NO$_\mathrm{x}$)!emissions of}
        from bauxite mining in Australia,

  \item Toxic tailings
        from tungsten\index{tungsten (W)}
        mining operations in Korea~\cite{Lee:2021tz}, and

  \item Deforestation\index{deforestation} and
        reduced forest quality~\cite{Kissinger:2020ut}
        to make way for rubber plantations\index{rubber plantations}
        in southeast Asia.

\end{itemize}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Prime example: carbon intensity of energy}
\label{sec:carbon_intensity_of_energy}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

As discussed in Chapter~\ref{chap:resource_intensity},
the prime example of resource extraction and consumption is energy.
Because CO$_2$ emissions\index{carbon dioxide (CO$_2$)!emissions of}
are a significant source of environmental impact
coming from energy consumption,
it follows that the prime example of 
environmental impact intensity of resource extraction and consumption
(\;\!\mft{X} in Equation~\ref{eq:IPARX}) is CO$_2$ emissions
in tonnes per MJ of energy provided.
Specifically, the prime example for impact intensity~\Xparen{}
is the CO$_2$ intensity of energy, $\mft{X}_{\text{CO}_2}$.

Figure~\ref{fig:LLNL_CO2_sankey} is a Sankey\index{Sankey diagram!CO$_2$ emissions} 
diagram of sources of CO$_2$ emissions from the U.S.\ economy in 2018.
However, in Figure~\ref{fig:LLNL_CO2_sankey} CO$_2$ emissions
from electricity generation stop at generation and are not attributed to those
who use the electricity, such as residential and commercial.
Table~\ref{tab:corrected_co2_emissions} shows the result of attributing 
CO$_2$ emissions to end uses,
thereby completing the picture of U.S.\ carbon emissions.\index{carbon dioxide (CO$_2$)!emissions of}
Attributing CO$_2$ emissions in this way 
makes it clear that the residential and commercial sectors
are actually responsible for a larger share of CO$_2$ emissions than 
Figure~\ref{fig:LLNL_CO2_sankey} would otherwise indicate.

\begin{figure}
\centering
\includegraphics[width=\linewidth]{chapters/ch06-ImpactIntensity/figures/Carbon_2018_United-States.png}
\caption{U.S.\ CO$_2$ emissions in 2018.
         CO$_2$ emissions from electricity production are not attributed to end uses.
         See Table~\ref{tab:corrected_co2_emissions}.
         \emph{Source}: \citet{Lawrence-Livermore-National-Laboratory:wp}.}
\label{fig:LLNL_CO2_sankey}
\end{figure}



<<US-Carbon-Table, results="asis">>=
US_CO2_by_sector <- readxl::read_excel(file.path("chapters", "ch06-ImpactIntensity", "datasets", "US-Carbon-Emissions.xlsx"),
                                       sheet = "data to plot") %>%
  dplyr::mutate(
    `CO2 share` = `CO2 share` * 100 # To put in % terms.
  ) %>% 
  dplyr::rename(
    `CO$_2$ emissions [Mt]` = `CO2 emissions allocated [million tonnes]`,
    `Proportion [\\%]` = `CO2 share`
  )

print(xtable::xtable(US_CO2_by_sector, digits = c(0, 0, 0, 1),
                     caption = "U.S.\ CO$_2$ emissions 2018 by sector with
                     CO$_2$ emissions from electricity generation attributed to
                     end uses by
                     fraction of electricity demanded.",
                     label = "tab:corrected_co2_emissions"),
      include.rownames = FALSE,
      include.colnames = TRUE,
      caption.placement = "top",
      type = "latex",
      sanitize.text.function = function(x) {x},
      booktabs = TRUE,
      table.placement = NULL)
@


The yearly rate of world CO$_2$ emitted since 1800 
is shown in Figure~\ref{fig:CarbonEmissionsGraph}.
Annual primary energy consumption is shown in Figure~\ref{fig:PrimaryEnergyGraph}.
The ratio of the lines in Figures~\ref{fig:CarbonEmissionsGraph} and
\ref{fig:PrimaryEnergyGraph} is the carbon intensity of primary energy,
as shown in Figure~\ref{fig:ImpactIntensityGraph}.
The line in Figure~\ref{fig:ImpactIntensityGraph}
demonstrates the long transition
from traditional biofuels to fossil fuels
evident in Figure~\ref{fig:PrimaryEnergyGraph}.

The biofuel-to-fossil fuel transition has
significant sustainability implications.
Traditional biofuels are carbon neutral,
because any CO$_2$ released by combustion was
already sequestered into the biomass as the plants grew.
Fossil fuels are not carbon neutral;
their combustion releases CO$_2$ that was sequestered millions of years ago.
As the world transitioned away from traditional biofuels toward fossil fuels,
the carbon intensity of energy rose.

On the other hand, use of traditional biofuels results in deforestation, erosion,
and other negative environmental effects (as well as being inefficient from an EROI 
perspective, as shown in Table~\ref{tab:eroi}).
The transition away from biofuel consumption results in cleaner urban air (especially after 
the transition from coal to natural gas for residential heating) as noted by~\cite{Gordon2016}.
Because having a healthy environment is what economists call a ``normal'' good,
\mft{I} should fall as \mft{A} rises, in general.
In \emph{some} ways, the transition away from traditional biofuels \emph{did} result
in reduced environmental impact, neglecting climate change concerns.
% Referencing Figure 5.3, the falling biomass PER GDP, doesn't seem appropriate here.

<<ImpactIntensityGraph, fig.cap="Carbon intensity of energy, $X_{\\text{CO}_2}$. The line represents the ratio of Figure~\\ref{fig:CarbonEmissionsGraph} and Figure~\\ref{fig:PrimaryEnergyGraph} in each year.">>=
carbon_intensity <- dplyr::inner_join(
  CO2_emissions,
  primary_energy %>%
    dplyr::group_by(Year) %>%
    dplyr::summarise(energy_EJ = sum(energy_EJ)),
  by = "Year"
) %>%
  dplyr::mutate(
    CO2_intensity_Mt_per_EJ = CO2_emissions_tonnes / 1e6 / energy_EJ,
  ) 

carbon_intensity %>%
  ggplot2::ggplot(mapping = ggplot2::aes_string(x = "Year", y = "CO2_intensity_Mt_per_EJ")) +
  ggplot2::geom_line(size = data_line_size,
                     colour = data_line_colour, 
                     linetype = data_linetype) +
  ggplot2::labs(x = NULL,
                y = expression("Carbon intensity of energy [Mt "*CO[2]/EJ*"]")) +

  MKHthemes::xy_theme()
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Reducing the carbon intensity of energy}
\label{sec:reducing_c}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Equation~\ref{eq:IPARX} shows that reducing any of the right-hand side terms to 0
will eliminate CO$_2$ emissions.
That is, if population~\Pparen{}, 
affluence~\Aparen{},
energy intensity of the economy ($R_{Ep}$, the prime example for \mft{R})
\emph{or} carbon intensity of energy $X_{CO_2}$ (the prime example for \mft{X})
go to zero,
CO$_2$ emissions will be eliminated.
Few people want to reduce population~\Pparen{} or affluence~\Aparen{}.
The primary energy intensity of the economy, $R_{Ep}$, is declining
(Figure~\ref{fig:EnergyIntensityGraph-Nordhaus}),
but not as fast as population (Figure~\ref{fig:PopulationGraph})
and affluence (Figure~\ref{fig:AffluenceGraph-Nordhaus}) are growing.
By the process of elimination, 
reducing the carbon intensity of energy is often considered to be the 
only politically and socially viable way to move in a sustainable direction
with respect to our prime examples, energy and CO$_2$ emissions.
(Note that other sustainability issues are likely to remain!)

Figure~\ref{fig:ImpactIntensityGraph} shows that the carbon intensity of energy
rose dramatically from 1800--1960, 
as use of fossil fuels came to dominate the world energy story.
(See Figure~\ref{fig:PrimaryEnergyGraph}.)
Since 1960, the carbon intensity of energy
has hovered around 63 Mt CO$_2$/EJ.
Thus, for the last 60 years, the carbon intensity of energy has been stubbornly constant.
It appears that eliminating CO$_2$ emissions by significantly reducing
the carbon intensity of energy ($X_{CO_2}$) will require unprecedented changes
to the world's primary supply.
But how?


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Transition to a low-carbon energy regime}
\label{sec:low_carbon_transition}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

There are at least five often-discussed options for
transitioning to a low carbon intensity energy supply:
(a) carbon capture and storage,
(b) carbon sequestration,
(c) carbon takeback obligation,
(d) carbon tax,
(e) nuclear electricity,
(e) biomass, and
(f) wind, water, and solar (WWS).
Each option has its own challenges and 
none has yet been implemented on a large enough scale to reduce CO$_2$ emissions;
see Figure~\ref{fig:CarbonEmissionsGraph}.
The subsections below discuss these options and their implementation challenges.


%++++++++++++++++++++++++++++++
\subsection{Carbon capture and storage}
\label{sec:ccs}
%++++++++++++++++++++++++++++++

Carbon capture and storage (CCS)\index{carbon capture and storage (CCS)}
is a way to continue using fossil fuels
during a transition to a low-carbon energy regime. 
In a CCS electricity plant, 
CO$_2$ emissions are captured at the smokestack
and routed underground.
The CO$_2$ is stored, presumably in perpetuity, in caverns or other underground formations.
CCS is not a low-carbon form of energy.
Rather, CCS is a way to avoid carbon \emph{emissions} from carbon-based energy production.

There are several challenges associated with CCS.
First, it has not been cost-effective.  
Petra Nova, the only CCS plant in the U.S., disposed of the CO$_2$ it captured
by injecting it into oil fields for enhanced oil recovery.
In 2020, low oil prices made this disposal infeasible, forcing Petra Nova to shut down.
This story illustrates the economic interrelation(s) among primary energy sources.

Second, a fossil-fuel power plant fitted with CCS technology 
must ensure that CO$_2$ emissions remain buried. 
If the CO$_2$ escapes to the atmosphere, the effort is ineffective.

Third, there are limited locations with the required underground geological formations 
for CCS.

Finally, CCS is not applicable to CO$_2$ emissions from transportation,
which is the plurality of CO$_2$ emissions; 
see Table \ref{tab:corrected_co2_emissions}.
It would be impractical to fit every car with a ``CO$_2$ diaper''
to collect CO$_2$ emissions for later injection underground.


%++++++++++++++++++++++++++++++
\subsection{Carbon sequestration}
\label{sec:carbon_sequestration}
%++++++++++++++++++++++++++++++

Carbon sequestration seeks to extract CO$_2$ from the atmosphere,
storing it in inert form.
One form of carbon sequestration is simply planting billions of trees.
A massive, worldwide afforestation effort would be required to extract
the additional carbon that has been added to the atmosphere since the industrial revolution.
In such a scheme, trees consume CO$_2$, and store it in their biomass.
Unfortunately, if the trees are burned or when they die and decompose, 
the CO$_2$ is returned to the atmosphere.

Alternatively, \emph{direct air capture} extracts CO$_2$ from the atmosphere 
directly, typically using huge banks of fans and an adsorbent.
Direct air capture is extremely energy intensive because of the heat needed
to regenerate the adsorbents. 
Additionally, because atmospheric CO$_2$ concentrations are low, massive amounts
of air need to be moved, which makes operating the fans expensive. 
Thirdly, some carbon sequestration technologies require expensive and/or rare
materials.
Various schemes have been proposed for how to alleviate some or all of these 
problems but none have been proven to work at scale.

One additional problem with carbon sequestration is what form should be used
ultimately to store the carbon. 
Geologic storage converts CO$_2$ to liquid form at high pressure and pumps it
into underground storage.
Biologic storage is when carbon is trapped in plant matter, soil, or aquatic
environments.
Perhaps, CO$_2$ could be converted to a stable chemical structure such as graphene.


%++++++++++++++++++++++++++++++
\subsection{Carbon takeback obligation}
\label{sec:ctbo}
%++++++++++++++++++++++++++++++

Another way to reduce CO$_2$ emissions over time is the 
carbon takeback obligation (CTBO)~\cite{Jenkins:2021tg}.
The CTBO is similar to product takeback policies
which require manufacturers to accept end-of-life product returns from consumers,
thereby keeping wastes (refrigerators, washers, dryers, computers, electronics, etc.)
out of landfills and 
contaminates out of the environment.

The climate change equivalent of a product takeback is the carbon takeback. 
Under a CTBO, fossil fuel producers and importers would be required 
to permanently sequester the carbon emitted from the fossil fuels they sell or import.
Industries that emit greenhouse gasses (cement making, etc.)
would also be required to sequester their emissions.
A CTBO does not specify \emph{how} the sequestration must occur,
but it specifies who is obliged to do the sequestration. 
Under a CTBO, fossil fuel producers and other emitting industries
would be free to pass the cost of carbon sequestration
to fossil fuel users and other product consumers (cement, e.g.),
thereby internalizing the cost of CO$_2$ emissions in the economy.
Consumers would still be free to purchase and use fossil fuels, 
but under a CTBO the true societal cost of fossil fuel consumption would be evident.

A progressive CTBO could be phased over several years.
In the first years, only, say, 10\% of emitted CO$_2$ would need to be sequestered.
A few years later, 20\%.
Then 30\%.
Eventually, fossil fuel producers and other emitting industries
would need to be sequester 100~\% of the
greenhouse gasses emitted from the use of their product.

There are several implementation challenges for CTBOs.
First, we will need to develop the expertise to 
sequester carbon on a scale never seen before.
At present, only 0.1\% of emitted carbon in sequestered~\cite[p.~2777]{Jenkins:2021tg}.
Second, policymakers will need to develop rules and laws for CTBOs, 
and enforcement mechanisms will need to be implemented.
Finally, lower-carbon alternatives will need to be developed for many 
commonplace technologies, including
transport (ground and air), 
building materials (especially cement), and 
building heating and cooling.


%++++++++++++++++++++++++++++++
\subsection{Carbon taxes and offsets}
\label{sec:carbon_tax_offsets}
%++++++++++++++++++++++++++++++

Carbon taxes impose financial penalties on emitters of greenhouse gasses.
Emitters pass costs to consumers who face higher prices for goods and services
created with carbon-intensive energy.
Consumers will, over time, prefer lower-cost goods, 
thereby incentivizing manufacturers and service providers
to use low-carbon energy.

Carbon offsets enable carbon emitters to
pay someone else to sequester or reduce carbon emissions.
Carbon emissions are traded as a financial instrument.
A market develops in which emissions and reductions are traded, 
with competition leading to low prices for net emission reductions.
As such, carbon offsets 
enable carbon emitters to shift the responsibility for implementing
emissions reductions.

Both carbon taxes and carbon offsets are 
financial approaches to encourage transitions to a low-carbon energy supply.
Both taxes and offsets nudge consumer and producer behaviors
in the direction of low-carbon energy supply.


%++++++++++++++++++++++++++++++
\subsection{Nuclear electricity}
\label{sec:nuclear_electricity}
%++++++++++++++++++++++++++++++

Nuclear power (an electricity source only)
may provide a bridge to a sustainable future.
Nuclear power emits little CO$_2$ during plant operation. 
However, the energy cost to construct a nuclear power plant 
is higher than other types of
electricity production plants.
In addition, 
it is energy-intensive to mine and refine uranium prior to its use
in a nuclear power plant. 
If the energy required to construct nuclear energy plants
and refine uranium comes from fossil fuels, 
significant CO$_2$ emissions will result from the transitions to nuclear electricity.

An additional consideration is the availability of unranium resources,
the topic of P6.\ref{question:nuclear_resources}.


%++++++++++++++++++++++++++++++
\subsection{Biomass}
\label{sec:biomass}
%++++++++++++++++++++++++++++++

In lieu of extracting CO$_2$ from the atmosphere,
we could stop emitting CO$_2$ from fossil fuel combustion in the first place!
One way is to transition away from fossil fuels 
to the energy mix used in the first half of the 19$^\mathrm{th}$ century,
namely exclusive use of traditional biofuels (wood and wood products).\index{biofuels}
(See Figure~\ref{fig:PrimaryEnergyGraph}.)
However, supplying the energy needs of today's economy would be impossible:
we don't have enough available arable land
to grow the required amount biomass.
(Proof of this statement is left for Project P6.\ref{item:biofuel_proof}.)
Even if there were enough land, growing crops requires unsustainable energy inputs 
(see Chapter \ref{chap:agriculture}), as well as water and chemical inputs.
Further, biomass by itself is not electricity or liquid fuel.
A conversion to biomass for the world's primary energy supply would also require 
worldwide replacement of today's fossil-fuel-dominated electricity infrastructure
with a fleet of biomass power plants.
And conversion to biomass would require build-out of a biomass-to-liquid-fuels conversion 
infrastructure that does not yet exist.
Finally, conversion to biomass will be accompanied by a reduction in $EROI$
(see Section~\ref{sec:masterE}).
The $EROI$ for fossil fuels is mostly greater than 20 (see Table \ref{tab:eroi}), while
the $EROI$ for corn ethanol is typically less than 2~\cite{Hammerschlag:2006uf}.


%++++++++++++++++++++++++++++++
\subsection{Wind, water, and solar}
\label{sec:wws}
%++++++++++++++++++++++++++++++

We could transition the world's energy system
to water (hydro), wind, and solar 
(WWS)~\cite{Jacobson:2011gc,Delucchi:2011gb}\index{water, wind, and solar (WWS)}
energy sources.
A transition to WWS would also require 
significant changes to the world's energy infrastructure, 
with many large challenges.
First, WWS energy resources produce electricity, not liquid fuels.
Thus, any economic sector that currently relies upon liquid fuels must be electrified.
An important example of the need to electrify is the transportation sector.
Today, transport is almost exclusively powered by liquid fossil fuels (gasoline and diesel).
Electrifying the world's transportation fleet is a prerequisite to a transition to WWS
and a zero-carbon economy.

There are two options for electrification of the world's transportation fleet: 
replacing all liquid fuel vehicles with electric vehicles or 
using electricity to make renewable fuels, such as hydrogen or biofuels, and 
then replacing all fossil-fuel vehicles with renewable-fuel vehicles. 
Replacing all liquid fuel vehicles with electric vehicles is slowly occurring today. 
Electrification of personal vehicles is happening from the top end of markets, 
with expensive offerings from companies such as Tesla.
Electrification has not yet penetrated meaningfully into the freight system,
including trucks, ships, and planes.
% This is discussed at length in research circles. Electric planes, biofuel planes,
% biodiesel or electric trucks. Maersk has committed to carbon-neutrality by 2050
% and is launching a bio-methanol ship in 2023.
% Hydrogen is not energy dense enough to be a transportation fuel but could 
% serve as efficient grid-scale energy storage (electrolysis by WWS, base-generation
% fuel cell generators for efficient discharge). However, we don't really have 
% materials yet to do this ``at scale.''

Second, wind and solar (the \emph{WS} in W\emph{WS}) are intermittent sources of electricity,
while today's electricity sources 
(coal, natural gas, nuclear, and hydro)
are not.
At present, electric grids accommodate only a fraction of intermittent electricity, much less than 100\%.
So a transition to wind and solar primary energy sources will require
redesign and re-implementation of electricity grids worldwide
to include electricity storage.
Battery storage on the required scale will require great quantities of rare earth metals 
and other exotic materials. 
Gravitational potential energy could supply storage with <~100\% 
round-trip efficiency.
Options for potential energy storage materials include 
water (with a pumped hydro plant)
or concrete with a system such as Energy Vault~\cite{Energy-Vault:uz}.

Third, in most areas of the world, 
the potential for expanding the production of hydro electricity is limited.
Most of the Americas, Europe, and Asia are already ``tapped out'' regarding hydropower.
Today, the potential for hydro is greatest in central Africa.
The proposed Grand Inga dam in the Democratic Republic of the Congo
would be the largest dam in the world and could house a 40--70 GW hydro power station.
Moreover, there are considerable negative environmental and social impacts from 
hydro projects, such as changes to soil salinity, silting, and the destruction
of communities located in the proposed reservoir.

Fourth, WWS systems are energy intensive to manufacture.
So the transition to a WWS future will require significant energy investment
in addition to significant financial investment.
If the energy investment to make WWS systems comes from fossil fuels,
significant CO$_2$ will be emitted during the transition
from today's energy regime to a WWS regime.


%++++++++++++++++++++++++++++++
\subsection{Speed of energy transitions}
\label{sec:Etransitions}
%++++++++++++++++++++++++++++++

Figure \ref{fig:ImpactIntensityGraph} shows that a transition to a new form(s)
of energy takes quite a long time to complete. It is costly both in terms of
money and resources, in particular, in terms of energy itself.
It takes energy to make energy-making machines!

Energy historians find that energy transitions often take decades to complete.
Roger Fouquet, has studied energy transitions of the UK in many economic sectors and 
across many energy technologies.
In a paper titled 
\emph{The slow search for solutions: Lessons from historical energy transitions by sector and service}, 
he finds that
``since the Industrial Revolution, it took, on average, 
nearly 50 years for energy transitions 
(i.e., the diffusion of energy sources and technologies) 
to unfold''~\cite[p.~6595]{Fouquet:2010tq}.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Revisiting the IPARX identity}
\label{sec:revisit_IPARX}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Chapters~\ref{chap:planetary_boundaries}--\ref{chap:impact_intensity}
show the evolution of all terms in the IPARX identity (Equation~\ref{eq:IPARX})
over the period 1800--2019
for the prime example of energy consumption and CO$_2$ emissions.
It is instructive to quantify the direction and magnitude of changes 
in the right-side terms (\:\!\mft{P}, \mft{A}, \mft{R}, and \mft{X}\:). 
To do so, we introduce a rate version of the IPARX equation.

In the rate version of the IPARX equation, each term is represented 
by an exponential rate of change (\mft{r}\:\!), measured in \%/year.
The rate version of the IPARX equation indicates 
which terms are moving in a sustainable direction (\mft{r} < 0) and
which terms are moving in an unsustainable direction (\mft{r} > 0).

\begin{equation} \label{eq:IPARX_rate}
  \mft{r}_\mft{I} \approx \mft{r}_\mft{P} + \mft{r}_\mft{A} + \mft{r}_\mft{R} + \mft{r}_\mft{X}
\end{equation}
%
Each rate (\mft{r}\:\!) is calculated by

\begin{equation} \label{eq:rate_calcs}
  \mft{r}_\mft{y} = \left[ \left( \frac{\mft{y}_2}{\mft{y}_1} \right) ^ \frac{\text{1}}{\mft{t}_2 - \mft{t}_1} - \text{1} \right] \times \text{100} \; ,
\end{equation}
%
where
\mft{r} is the rate of change in \%/year, 
\mft{y} is one of \mft{I}, \mft{P}, \mft{A}, \mft{R}, or \mft{X}, 
subscript ``2'' indicates a later year, and 
subscript ``1'' indicates an earlier year.

<<RatesOfChange>>=
rate_func <- function(df) {
  # Each df has structure
  # t1   y1
  # t2   y2
  yrs <- df[[2,1]] - df[[1,1]]
  # r = (y2/y1)^(1/t2-t1) - 1
  (df[[2,2]]/df[[1,2]])^(1/yrs) - 1
}

rate_to_string <- function(rate, include_units = TRUE) {
  if (include_units) {
    return(paste0(format(round(rate*100, 1), nsmall = 1), "~\\%/yr"))
  }
  format(round(rate*100, 1), nsmall = 1)
}

trim_for_chapter <- function(.df, var, years = c(1800, 2019)) {
  .df %>%
    dplyr::filter(Year %in% years) %>% 
    dplyr::select(Year, .data[[var]])
}

impact <- CO2_emissions %>%
  dplyr::select(-Country)
population <- region_pop %>%
  dplyr::filter(Country == "World") %>%
  dplyr::select(Year, total_population)
affluence <- world_gdppc_Nordhaus 
resource_intensity <- energy_intensity %>%
  dplyr::select(Year, primary_energy_type, energy_per_GDP_MJ_per_dollar) %>% 
  dplyr::group_by(Year) %>% 
  dplyr::summarise(energy_per_GDP_MJ_per_dollar = sum(energy_per_GDP_MJ_per_dollar))
carbon_intensity_of_resources <- carbon_intensity %>%
  dplyr::select(Year, CO2_intensity_Mt_per_EJ)

iparx_df <- impact %>% 
  dplyr::full_join(population, by = "Year") %>% 
  dplyr::full_join(affluence, by = "Year") %>% 
  dplyr::full_join(resource_intensity, by = "Year") %>% 
  dplyr::full_join(carbon_intensity_of_resources, by = "Year") %>%
  dplyr::mutate(
    CO2_emissions_tonnes = CO2_emissions_tonnes / 1e9, # convert tonnes to giga-tonnes
    total_population = total_population / 1e9, # convert total population to billions
    gdppc_2017_intl_dollars_per_capita = gdppc_2017_intl_dollars_per_capita / 1000 # convert $/person to k$/person
  ) %>% 
  magrittr::set_names(c("Year", "\\mft{I} [Gt/yr]", "\\mft{P} [billions]", "\\mft{A} [k\\$/person]", 
                        "\\mft{R} [MJ/\\$]", "\\mft{X} [Mt/EJ]"))

# Extract the data to be used in the equation
r_I_220 <- iparx_df %>% trim_for_chapter(var = "\\mft{I} [Gt/yr]") %>% rate_func()
r_P_220 <- iparx_df %>% trim_for_chapter(var = "\\mft{P} [billions]") %>% rate_func()
r_A_220 <- iparx_df %>% trim_for_chapter(var = "\\mft{A} [k\\$/person]") %>% rate_func()
r_R_220 <- iparx_df %>% trim_for_chapter(var = "\\mft{R} [MJ/\\$]") %>% rate_func()
r_X_220 <- iparx_df %>% trim_for_chapter(var = "\\mft{X} [Mt/EJ]") %>% rate_func()

r_I_20 <- iparx_df %>% trim_for_chapter(var = "\\mft{I} [Gt/yr]", years = c(2000, 2019)) %>% rate_func()
r_P_20 <- iparx_df %>% trim_for_chapter(var = "\\mft{P} [billions]", years = c(2000, 2019)) %>% rate_func()
r_A_20 <- iparx_df %>% trim_for_chapter(var = "\\mft{A} [k\\$/person]", years = c(2000, 2019)) %>% rate_func()
r_R_20 <- iparx_df %>% trim_for_chapter(var = "\\mft{R} [MJ/\\$]", years = c(2000, 2019)) %>% rate_func()
r_X_20 <- iparx_df %>% trim_for_chapter(var = "\\mft{X} [Mt/EJ]", years = c(2000, 2019)) %>% rate_func()

# r_I_check should be same as r_I
r_I_check_220 <- r_P_220 + r_A_220 + r_R_220 + r_X_220
r_I_check_20 <- r_P_20 + r_A_20 + r_R_20 + r_X_20

stopifnot(abs(r_I_check_220 - r_I_220) < 0.0005)
stopifnot(abs(r_I_check_20 - r_I_20) < 0.0005)
@


Select data from Figures~\ref{fig:CarbonEmissionsGraph},
\ref{fig:PopulationGraph}, 
\ref{fig:AffluenceGraph-Nordhaus}, 
\ref{fig:EnergyIntensityGraph-Nordhaus}, 
and~\ref{fig:ImpactIntensityGraph} 
are shown in Table~\ref{tab:iparx_select_years}.
Data from Table~\ref{tab:iparx_select_years}
can be used with Equation~\ref{eq:rate_calcs}
to answer the question, 
``what equivalent annual rate of change (\mft{r}\:\!) 
would give the same start and end points
in 1800 and 2019 
or
2000 and 2019?''
The answers are shown in Equation~\ref{eq:IPARX_rate_with_numbers}.


<<IPARX_Table, results="asis">>=
years_for_rate_table <- c(1800, 1850, 1900, 1950, 1970, 2000, 2010, 2019)

print(xtable::xtable(iparx_df %>% 
                       dplyr::filter(Year %in% years_for_rate_table), digits = c(0, 0, 3, 2, 2, 2, 2),
                     caption = "IPARX terms for selected years in Figures~\\ref{fig:CarbonEmissionsGraph}, \\ref{fig:PopulationGraph}, \\ref{fig:AffluenceGraph-Nordhaus}, \\ref{fig:EnergyIntensityGraph-Nordhaus}, and~\\ref{fig:ImpactIntensityGraph}. With Equation~\\ref{eq:IPARX_rate_with_numbers} these data allow us to see whether the world is becoming more sustainable or less over time and why.",
                     label = "tab:iparx_select_years"),
      include.rownames = FALSE,
      include.colnames = TRUE,
      caption.placement = "top",
      type = "latex",
      sanitize.text.function = function(x) {x},
      booktabs = TRUE,
      table.placement = NULL)
@


\begin{equation}
\label{eq:IPARX_rate_with_numbers}
\footnotesize
\begin{tabular}{rccccccccc}
     & $\mft{r}_\mft{I}$     & $\approx$ & $\mft{r}_\mft{P}$    & $+$ & $\mft{r}_\mft{A}$   &   $+$ & $\mft{r}_\mft{R}$                       & $+$ & $\mft{r}_\mft{X}$                         \\
1800--2019 & \Sexpr{rate_to_string(r_I_220)} & $\approx$ & \Sexpr{rate_to_string(r_P_220)} & $+$ & \Sexpr{rate_to_string(r_A_220)} &
                                    $-$ & \Sexpr{rate_to_string(abs(r_R_220))} & $+$ & \Sexpr{rate_to_string(r_X_220)}   \\
2000--2019 & \Sexpr{rate_to_string(r_I_20)} & $\approx$ & \Sexpr{rate_to_string(r_P_20)} & $+$ & \Sexpr{rate_to_string(r_A_20)} &
                                    $-$ & \Sexpr{rate_to_string(abs(r_R_20))} & $+$ & \Sexpr{rate_to_string(r_X_20)}   \\
\end{tabular}
\normalsize
\end{equation}

Equation~\ref{eq:IPARX_rate_with_numbers} shows that carbon emissions 
(Figure~\ref{fig:CarbonEmissionsGraph})
are increasing 
at an average rate of $\mft{r}_\mft{I} =$ \Sexpr{rate_to_string(r_I_220)}
since pre-industrial times (1800--2019)
and $\mft{r}_\mft{I} =$ \Sexpr{rate_to_string(r_I_20)}
over the last two decades (2000--2019). 
(The data in Table~\ref{tab:iparx_select_years} and 
Equation~\ref{eq:IPARX_rate_with_numbers}
can be used to discern
trends over other periods of time. 
See Project~P6.\ref{item:iparx_calcs}.)
The declining energy intensity of the economy term ($\mft{r}_\mft{R}$ < 0)
is the only term in the IPARX identity
putting downward pressure on the CO$_2$ emissions growth rate ($\mft{r}_\mft{I}$).
All other terms on the right side of Equation~\ref{eq:IPARX_rate_with_numbers}
are greater than zero and are driving CO$_2$ emissions upward.
Interestingly, the impact intensity of energy ($\mft{r}_\mft{X}$)
is smaller (\Sexpr{rate_to_string(r_X_20)})
in the past two decades than over the past two centuries
(\Sexpr{rate_to_string(r_X_220)}), because 
the world's transition to a fully carbonized energy system
was largely complete by 1970.
(See Figure~\ref{fig:ImpactIntensityGraph}.)
The beneficial effect of the declining resource intensity of the economy ($\mft{r}_\mft{R}$ < 0)
is growing over time 
($\mft{r}_\mft{R} = -$\Sexpr{rate_to_string(abs(r_R_220))} for 1800--2019 and
$\mft{r}_\mft{R} = -$\Sexpr{rate_to_string(abs(r_R_20))} for 2000--2019).

%^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
\begin{mcframe}[0.90\textwidth](0.85\textwidth)
%^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The positive terms in Equation~\ref{eq:IPARX_rate_with_numbers}
represent sources of our sustainability challenges:
rising population ($\mft{r}_\mft{P}$ > 0), 
rising affluence ($\mft{r}_\mft{A}$ > 0), and 
expanded use of fossil fuels ($\mft{r}_\mft{X}$ > 0).

\end{mcframe}

The IPARX identity and 
the prime example (energy consumption and CO$_2$ emissions)
show that we are heading in an unsustainable direction,
because CO$_2$ emissions are growing over time.
In other words,
Part~\ref{part:IPARX} (Chapters~\ref{chap:planetary_boundaries}--\ref{chap:impact_intensity})
has described the \emph{what} of our sustainability challenges.
Next, Part~\ref{part:sustainability_challenges}
(Chapters~\ref{chap:households}--\ref{chap:land_use_urban_planning})
explores reasons \emph{why} we face these challenges
in several sectors of the economy.
Finally, Part~\ref{part:actions}
(Chapters~\ref{chap:government} and~\ref{chap:personal_action})
provides suggestions for \emph{how} to respond, 
collectively and personally.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{IPARX interactions}
\label{sec:iparx_interactions}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The IPARX identity
appears to be a straight multiplication of independent terms
(\:\!\mft{P}, \mft{A}, \mft{R}, and \mft{X}\:).
But it is not.
There are interactions among the terms that deserve attention.
In this section, we note four such interactions
for the prime example of energy and CO$_2$ emissions.
The interactions among IPARX equation terms
are an example of the interconnected character of human society as we know it.
Indeed, policies directed at improving one term of the IPARX identity
will always have effects (intentional and unintentional)
on other terms of the IPARX identity.

%^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
\begin{mcframe}[0.90\textwidth](0.85\textwidth)
%^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Former U.S.\ representative Vernon Ehlers'
many years in education and government led him to quip frequently
``you can never do only one thing.''

\end{mcframe}


%++++++++++++++++++++++++++++++
\subsection{The rebound effect}
\label{sec:rebound_effect}
%++++++++++++++++++++++++++++++

% When energy efficiency is deployed as a means of reducing CO$_2$ emissions,
% the carbon intensity of energy (\Xparen{} in the IPARX identity) will go down.
Energy efficiency is widely seen as a means of reducing CO$_2$ emissions.
The thinking goes that either the resource intensity (\:\!\mft{R} in the IPARX identity, 
Equation~\ref{eq:IPARX}) 
or impact intensity~\Xparen{}, or both,
will go down as efficiency rises.
However, energy efficiency is known to stimulate economic activity 
by a mechanism called the ``rebound effect''~\cite{Brockway:2021ww},
wherein monetary savings (from reduced energy consumption at a newly-efficient device)
are reinvested, leading to economic growth.
Economic growth raises the GDP of an economy,
so affluence~\Aparen{} will increase.
As \mft{A} increases, energy consumption will increase.
Whether energy efficiency actually saves energy and actually saves CO$_2$ emissions
depends on the strength of the rebound effect.
When rebound effect is so large as to wipe out the initial energy savings,
``backfire'' is said to occur~\cite{Sorrell:2009cg,Sorrell:2010ul}.
Backfire is a threat to a low-carbon future~\cite{Brockway:2017a}.
Thus, we must be careful about crafting policies to address 
the \mft{R} or \mft{X} terms in the IPARX identity.
We may inadvertently affect \mft{A} with the consequence of undoing 
the good we intended.


%++++++++++++++++++++++++++++++
\subsection{Affluence and population}
\label{sec:affluence_and_population_interaction}
%++++++++++++++++++++++++++++++

As discussed in Chapter~\ref{chap:population}, 
population depends on many factors. 
(For one example of the dependencies of population, 
see the causal loop diagram from the World3 model
shown in Figure~\ref{fig:World3loops}.)
One clear trend from history is that increasing affluence
leads to reduced population growth rate.
I.e., an increase in \mft{A} leads to a decrease in the rate of growth of \mft{P}.
Thus, the affluence and population terms of the IPARX equation
are not independent.


%++++++++++++++++++++++++++++++
\subsection{GDP and energy}
\label{sec:gdp_and_energy_interaction}
%++++++++++++++++++++++++++++++

The relationship between energy consumption and GDP
exposes another interaction among the IPARX terms
for the primary example of energy consumption and CO$_2$ emissions.
Historically, as GDP (equal to $\mft{P} \times \mft{A}$ in Equation~\ref{eq:IPARX}) increases, 
primary energy consumption also rises,
as shown in Figure~\ref{fig:E_vs_GDP_graph}.

<<E_vs_GDP_graph, fig.cap = "World primary energy consumption and world GDP.">>=
egdp_df <- primary_energy %>% 
  dplyr::group_by(Year) %>%
  dplyr::summarise(energy_EJ = sum(energy_EJ)) %>%
  dplyr::left_join(world_gdp_Nordhaus, by = "Year") %>%
  dplyr::mutate(
    gdp_trillions = world_gdp_2017_intl_dollars / 1e12
  )

egdp_df %>%
  ggplot2::ggplot(mapping = ggplot2::aes(x = gdp_trillions, y = energy_EJ)) +
  ggplot2::geom_line(size = data_line_size, 
                     colour = data_line_colour,
                     linetype = data_linetype) + 
  ggplot2::labs(x = "GDP [trillion 2017 Intl. $]", 
                y = "Primary energy consumption [EJ]") +
  
  MKHthemes::xy_theme()
@


However, the concave downward nature of Figure~\ref{fig:E_vs_GDP_graph} indicates that
each additional dollar of GDP requires incrementally less energy consumption
than the dollar before.
The line in Figure~\ref{fig:E_vs_GDP_graph} is concave downward because
the primary energy intensity of the economy ($\mft{I}_{\!\mft{Ep}}$)
has been decreasing over time,
as shown in Figure~\ref{fig:EnergyIntensityGraph-Nordhaus}.
Thus, as GPD ($\mft{P} \times \mft{A}$\:\!) rises, 
the primary energy intensity of the economy
(\:\!\mft{R} in the IPARX equation for the prime example) 
is expected to fall, 
as it has been for 220 years.
(Recall from Section~\ref{sec:energy_intensity_of_the_economy}, 
however, that \mft{R} is falling over time primarily because
per-dollar consumption of sustainable biomass is falling over time.
Ironically, unsustainable per-dollar fossil fuel consumption is more constant 
than sustainable per-dollar biomass consumption over time.
See Figure~\ref{fig:per_gdp_material_use}.)

\mft{R} is a type of economic intensity
that represents the effectiveness of using energy to make GDP.
This fact raises an interesting question:
can we use improved economic effectiveness 
(decreasing \mft{R}, brought about by rising energy efficiency)
to reduce environmental impacts (\:\!\mft{I} in Equation~\ref{eq:IPARX}, 
CO$_2$ emissions being the prime example)?
It certainly helps, as decreasing \mft{R} puts downward pressure on \mft{I} in Equation~\ref{eq:IPARX}.
However, recent research indicates that growing energy efficiency
(and declining \mft{R}) has never reduced energy consumption or environmental impacts, 
at least at the worldwide level~\cite{Brockway:2021ww}.
The rebound effect (Section~\ref{sec:rebound_effect}) is thought to be a strong candidate
for the reason why efficiency has not led to decreases
in energy consumption and CO$_2$ emissions over time.
Indeed, a circular trap exists.
Energy efficiency is known to stimulate economic growth, and 
increased economic activity leads to more energy consumption.
Because of interactions between energy and the economy, 
it is hard to see how energy efficiency alone 
leads to reduced energy consumption and CO$_2$ emissions.
In other words, it is hard to see how efficiency 
can decouple energy consumption from economic activity.
So long as energy consumption generates CO$_2$ emissions, 
it is hard to see how efficiency can decouple environmental impacts
from economic activity.

Economic growth, per-se, is not problematic.
However, when economic activity requires energy and energy consumption 
causes CO$_2$ to be emitted,
economic growth leads to sustainability challenges.
Reducing the carbon intensity of energy 
(the prime example for \mft{X} in Equation~\ref{eq:IPARX})
is one way to limit the environmental impacts of economic activity.
Interactions associated with a transition to low-carbon energy supplies
are the topic of the next section.


%++++++++++++++++++++++++++++++
\subsection{Renewables}
\label{sec:renewables_interaction}
%++++++++++++++++++++++++++++++

The transition to renewable energy sources 
is expected to reduce the CO$_2$ intensity of energy consumption
(in the prime example), 
if the CO$_2$ avoided by renewable generation over the lifetime of a renewable device
(say a photovoltaic solar panel)
is less than the CO$_2$ embodied
in the renewable device. 
That said, many advocates of Green Growth, a Green New Deal, and similar public policies 
promote the idea that a transition to green infrastructure, including renewable energy,
will stimulate economic growth and increase affluence.
If they are right, 
a renewables-driven decrease in \mft{X} would lead to an increase in \mft{A}
in the IPARX equation (Equation~\ref{eq:IPARX}).
The strength of each effect ($X \downarrow$, $A \uparrow$) 
will determine whether Green Growth or a Green New Deal will actually decrease 
environmental impacts~\Iparen{} or CO$_2$ emissions (in the prime example).


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Further Reading}\index{further reading}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Edward Humes, \emph{Garbology: Our dirty love affair with trash}, New York: Avery, 2012.\\

\noindent
Daniel Yergin, \emph{The new map: Energy, climate, and the clash of nations},
London: Penguin, 2020.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{See Also}\index{see also}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Energy Vault simulation:  \\ \url{www.vimeo.com/335818817}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Questions}\index{questions}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{questions}

\item Do renewable energy sources have ``emissions?'' If so, what are they?
        Make reference to Equation \ref{eq:IPARX}. At a minimum, discuss
        solar photovoltaic, wind turbines, hydro power, and renewable biofuels.

\item Fossil fuels have environmental impacts other than CO$_2$. 
      One example is oil spills,
      such as the Exxon Valdez and the Deep Water Horizon disasters.
      (The International Tanker Owners Pollution Federation reports ``only'' 18 oil
      spills larger than 700 tonnes for the period 2010-2019 versus 245 in the 1970s.) 
      Other examples include environmental impacts from hydraulic fracking
      fluids; air quality issues associated with burning fossil fuels such as
      soot, smog, and ozone; and soil contamination from leaking underground 
      fuel storage tanks.
      There is a tendency to approach each of these impacts
      as a separate problem and to invent technological fixes specific to each 
      problem, which is often a successful approach. 
      Indeed, the rate of oil spills has gone down due to better technology. 
      However, these technological solutions come with their own costs, risks, 
      and inherent tradeoffs.
      Give some examples of the tradeoffs inherent in pollution prevention technologies.
      How do we manage tradeoffs among different types of solutions?
      
\item Energy historian Roger Fouquet found that it has taken, historically, on average, 50 years
      to transition from one energy source to another.
      At this moment in time, it is unlikely that humanity has 50 years
      to effect a transition to renewable sources of energy
      to avoid irreversible effects of climate change.
      What should we do?
      Give up on mitigation and focus on adaptation?
      Find a way to do better than the 50-year average duration for an energy transition?
      If so, what are those ways? 
       
\item Expanding on the issues raised in the previous questions, 
      nuclear power has had its own environmental issues. 
      Disasters such Fukushima Daiichi, Three-Mile Island, and Chernobyl come to mind. 
      High-level waste is another. 
      Coal power plants in the Midwest region have emitted 
      enough mercury that fish in the Great Lakes are not safe for consumption
      by children or women of child-bearing age. 
      How do you make decisions about trading off different types of 
      environmental impacts?
      Which impacts are more acceptable? Which are less acceptable?
      
\item The naive tendency is to read the previous three questions and just say that
      all impacts are bad, which is true by definition of the word ``impact''
      but it is not helpful. The more interesting and helpful question is the 
      debate between a cost/benefit perspective (do the benefits provided by this
      form of energy outweigh the costs?) and a sustainability perspective
      (``is this form of energy sustainable and, if so, for how long?'').
      Do you lean more to the  cost/benefit perspective or the sustainability 
      perspective and why? 
      Are you using a weak or strong sustainability criterion?
      
\item Some people object to wind turbine because they kill birds. 
      The truth is, all human structures kill birds. 
      What are the alternatives (to having wind turbines at all)?
      What is the cost/benefit analysis of having wind turbines?
      Who does the analysis and makes the decisions about whether to have wind
      turbines and where to site them?
      Do birds get a voice in the decision? Should they?
      If so, who speaks for the birds?
      What about other animals, say clams or ants? 
      What about trees or the wind itself?
      What would your assumptions have to be to answer yes to any of these questions?

\item Which would you prefer, a biomass energy system or a water-wind-solar (WWS)
      energy system? Why?

\item What would be the consequences of a reduction in $EROI$ that would accompany 
      a conversion to a biofuel-based energy system?
        
\item One issue with a fully WWS electricity grid is the supposed need for significant
      energy storage. 
      Is grid-scale storage really required or is it just something we would like 
      to have? 
      How can you tell?

\item Consider the energy transition shown in Figure \ref{fig:ImpactIntensityGraph}.
      What does Figure \ref{fig:ImpactIntensityGraph} indicate about the length
      of time needed to transition to global carbon-free energy?
      Why did we go from a low-carbon economy (such as in 1800) to the high-carbon
      economy we have today? 

\item Should the transition to renewable energy sources be actively managed 
      (for example by government policy) or should we let the ``invisible hand
      of the market'' manage the transition for us? Why?
      Are your reasons strictly because of the outcome(s) you imagine? 
      What assumptions are you making that lead to those outcomes?
      Or do you have philosophical reasons to prefer active versus passive 
      management?
      Who is actually making the decisions about transitions to renewable energy
      (or not)?

\item Find the proportion of renewable energy in the world's energy mix today.
        Does this proportion indicate that we are far into the transition to a 
        low-carbon energy regime?

\item Argue for and against making Table \ref{tab:corrected_co2_emissions}.
      What does Table \ref{tab:corrected_co2_emissions} show that Figure
      \ref{fig:LLNL_CO2_sankey} doesn't (and vice versa)?
      Which do you find more helpful? Why?
      What sorts of decisions is each most helpful with?
      
\item Do you agree with the process of elimination in Section \ref{sec:reducing_c}?
      Are there other approach(es)? If so, what are they?
      What assumptions lead you to prefer one approach over another? % degrowth vs. techno optimists.

\item Should carbon capture and storage/sequestration be pursued as a stop-gap
      measure (until we get fully renewable energy)?
      What is your criteria for making that decision?
      Under what circumstances would your answer change?
      
\item The big issue for carbon capture and storage/sequestration (CCS) is who are the 
      stakeholders -- who pays and who benefits?
      ``It's too expensive'' is just another way of saying ``we don't value that
      very much.'' Are there legal or financial arrangements that could be made 
      that would sufficiently incentivize CCS such that it would be profitable?
      If so, why hasn't this been done already?

\end{questions}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Projects}\index{projects}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{projects}

  \item Investigate the energy available in a hectare of biomass production.
        How many hectares of biomass would need to be harvested annually
        to supply today's energy needs?
        How much available arable land exists in the world?
        What fraction of available arable land would be required to transition
        to a biomass-based energy system? \label{item:biofuel_proof}
        
  \item Research the potential for CO$_2$ storage in graphene. 
        What are the energy requirements for such a scheme?
        How many additional solar panels would be needed to 
        convert a ton of CO$_2$ to graphene?
        
  \item Research the Petra Nova carbon capture and storage (CCS) plant.
        What is the feasibility of replicating the Petra Nova scheme
        to all fossil fuel electricity power plants in the U.S.?
        In the World?
        What has been the cost to implement the Petra Nova plant?
        Who paid that cost?
        If the Petra Nova plant can't be replicated to all power plants, 
        are there other feasible options for CCS?

  \item Electrification of the world's transportation system is likely to be a costly endeavor.
        Find the number of petroleum-powered cars in service today. 
        Find a typical cost of an electric car today. 
        What is an estimated cost of electrifying the vehicle fleet?
        What fraction of world GDP does this cost represent?
      
  \item Research the countries with the largest fractions of intermittent 
        electricity generation (wind and solar).
        What features of those countries allow large fractions of 
        intermittent generation? 
        What would happen to the electricity grid in those countries 
        if the fraction of intermittent generation went to 100\%?
        
  \item Research and rank the EROI of many primary energy sources, 
        including fossil fuels and renewables such as biofuels.
        What does your ranking imply for transitions to a low-carbon energy regime?
        Critique how your sources drew the boundaries
        around which they're calculating that EROI.
        
  \item What would have to be true for the world to be able to implement a 100\% WWS energy system?
        
  \item It has been argued that the transition to a low-carbon energy regime
        is a ``grand challenge'' that will require funding levels 
        that rival the Apollo program, President Johnson's ``Great Society'' initiatives,
        and President Reagan's ``Star Wars'' program~\cite{Heun:2008vu}.
        Find several updated estimates of the costs for these and other large 
        government programs.
        Compare to estimates to effect a transition to a low-carbon energy regime.
        
  \item Calculate land required to convert all energy production to solar sources
        in the U.S. 
        What effect would a fully-solar energy infrastructure have on natural landscape?
        Where would you locate the solar panels?
        What transmission issues would emerge?
  
  \item What are the other resource implications of a WWS transition? 
        E.g., do we have enough niobium (Nb)\index{niobium (NB)} for the wind turbines
        required to implement a WWS energy supply? 
        
  \item Derive Equation~\ref{eq:IPARX_rate} from Equation~\ref{eq:IPARX}.
        You will use $(1 + r_1)(1 + r_2) \approx r_1 + r_2 + 1$ for $r_1, r_2 <\!\!\!< 1$
        in the derivation.
  
  \item Verify the calculations in Equation~\ref{eq:IPARX_rate_with_numbers}
        using data from Table~\ref{tab:iparx_select_years}.
        Then recalculate the terms in Equation~\ref{eq:IPARX_rate_with_numbers} 
        for the last 69 years only (1950--2019), 
        for the last 49 years only (1970--2019), and
        for the last 9 years only (2010--2019).
        How are the results similar to or different from the results 
        of Equation~\ref{eq:IPARX_rate_with_numbers}? \label{item:iparx_calcs}
        
  \item After many years of studying energy-economy interactions and the rebound effect, 
        \citet{Sorrell:2010ul} advanced five controversial propositions:
        % 
        \begin{enumerate} [label=(\arabic*)]

          \item the rebound effects from energy efficiency improvements are significant 
                and limit the potential for decoupling energy consumption from economic growth; 

          \item the contribution of energy to productivity improvements and economic growth 
                has been greatly underestimated;
        
          \item the pursuit of improved efficiency needs to be complemented by an ethic of sufficiency;
  
          \item sustainability is incompatible with continued economic growth in rich countries; and 
  
          \item a zero-growth economy is incompatible with a fractional reserve banking system.

        \end{enumerate}

        Sorrell's propositions suggest that 
        interactions between energy and the economy are so pervasive that
        a deep rethinking of the structure of society is warranted
        if we are to address, in a meaningful way, 
        the sustainability challenges that we face.
        Read Sorrell's paper and write a report that evaluates 
        the five propositions.
        Compare and contrast the five propositions with prevailing cultural norms in your society.
        Assess the necessity, desirability, and feasibility of reconfiguring society 
        as suggested in the article.
        
  \item At the end of Chapter~\ref{chap:impact_intensity}, you have learned about all four 
        right-side terms of the IPARX equation (Equation~\ref{eq:IPARX}).
        Write a paper that discusses each term and suggests your favored policy 
        to reduce the magnitude of each term. 
        Next look into the
        \href{EnROADS climate simulator}{https://www.climateinteractive.org/tools/en-roads/}
        and find its policy options for addressing climate change. 
        Which of your favored policies appears in the EnROADS options?
        Now choose a suite of policies in EnROADS that includes as many of your favored policies as possible.
        Can you achieve less than 1.5~\degC{} of warming?
        In the paper, describe the suite of policies you chose
        and consider their technical and political feasibilities.
        
  \item Research the availability of uranium resources. 
        What are the reserves?
        Is our current consumption rate weakly sustainable? \label{question:nuclear_resources}

\end{projects}



\cleardoublepage

