% The next command tells RStudio to do "Compile PDF" on book.Rnw,
% instead of this chapter, thereby eliminating the need to switch back to book.Rnw 
% before making the book.
%!TEX root = ../../book.Rnw

\chapter{Agriculture}
\label{chap:agriculture}


% https://thecounter.org/climate-change-eat-less-meat-plant-based-impossible-burger-regenerative-ranching
% The “eat less meat” movement is growing. Does it distort science? by Lynne Curry

% https://globalecoguy.org/beef-rules-d5bbf65a24e3
% https://globalecoguy.org/farming-our-way-out-of-the-climate-crisis-c235e1aaff8d
% See PDFs in the refs folder.

% http://i-peel.org/homepage/meat/
% https://theconversation.com/yes-eating-meat-affects-the-environment-but-cows-are-not-killing-the-climate-94968
% https://www.tabledebates.org/publication/grazed-and-confused
% LCA of White Oaks Farms: https://blog.whiteoakpastures.com/hubfs/WOP-LCA-Quantis-2019.pdf

% https://www.nationalacademies.org/news/2018/07/new-report-identifies-five-breakthroughs-to-address-urgent-challenges-and-advance-food-and-agricultural-sciences-by-2030
%% Buy the PDF, get a free hat, a $5 value for $55
% https://www.nap.edu/catalog/25059/science-breakthroughs-to-advance-food-and-agricultural-research-by-2030



\cleardoublepage 

